"""Audit database provenance for compiled kMC event-set rates."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict, deque
from copy import deepcopy
from dataclasses import dataclass
import hashlib
import json
import math
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tempfile
from typing import Any
import warnings

import numpy as np
from scipy.optimize import OptimizeWarning, curve_fit, fsolve

from rmgpy.data.kinetics.database import KineticsDatabase
from rmgpy.data.kinetics.family import KineticsFamily, _make_rule
from rmgpy.data.rmg import RMGDatabase
from rmgpy.data.thermo import ThermoDatabase, ThermoGroups
from rmgpy.kinetics.arrhenius import ArrheniusBM, get_w0s
from rmgpy.kinetics.model import KineticsModel
from rmgpy.kinetics.uncertainties import rank_accuracy_map
from rmgpy.kmc.compiler import (
    DEFAULT_T_GRID,
    EventSetCompiler,
    PS_FAMILY_CANDIDATES,
    PS_PROXY_UNITS,
    ps_proxy_set,
    validate_artifact,
)


FLAG_TERMS = (
    "Kruse",
    "Broadbelt",
    "Levine",
    "polystyrene",
    "polyethylene",
    "polypropylene",
    "polymer",
    "pyrolysis",
    "TGA",
    "thermogravimetr",
    "oligomer",
    "plastic",
    "Poutsma",
)
RATE_REPRODUCTION_RTOL = 1.0e-5
ORACLE_CONTROL_FAMILY = "Bimolec_Hydroperoxide_Decomposition"
LEGACY_SINGLE_REACTION_SWITCH_COMMIT = (
    "d0126887698c3ea04d2391e3389991d1b381af54"
)
LEGACY_TEMPERATURE_GRID = (
    300.0,
    500.0,
    600.0,
    700.0,
    800.0,
    900.0,
    1000.0,
    1100.0,
    1200.0,
    1500.0,
)
LEGACY_TREE_THERMO_LIBRARIES = (
    "Klippenstein_Glarborg2016",
    "BurkeH2O2",
    "thermo_DFT_CCSDTF12_BAC",
    "DFT_QCI_thermo",
    "primaryThermoLibrary",
    "primaryNS",
    "NitrogenCurran",
    "NOx2018",
    "FFCM1(-)",
    "SulfurLibrary",
    "SulfurGlarborgH2S",
    "SABIC_aromatics",
)
LEGACY_NODE_SPECS = (
    (
        "ac50fffc09b2ab997f163fab1107d6a8379adcdb",
        "Disproportionation",
        "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-4C-R_Ext-4C-R",
    ),
    (
        "ac50fffc09b2ab997f163fab1107d6a8379adcdb",
        "Disproportionation",
        "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-7C-R",
    ),
    (
        "ac50fffc09b2ab997f163fab1107d6a8379adcdb",
        "Disproportionation",
        "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C",
    ),
    (
        "ac50fffc09b2ab997f163fab1107d6a8379adcdb",
        "Disproportionation",
        "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_1R!H-inRing",
    ),
    (
        "5316e3e16bc252395ca90b5693244751a1e16d1b",
        "R_Recombination",
        "Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_1C-inRing_Ext-1C-R_N-Sp-3R!H-1C_Ext-2R-R_N-2R-inRing_Sp-4R!H-2R",
    ),
    (
        "5316e3e16bc252395ca90b5693244751a1e16d1b",
        "R_Recombination",
        "Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R",
    ),
)


def _persist_generated_kinetics(kinetics):
    """Apply the same finite representation used when rules.py is saved."""
    context = KineticsDatabase().local_context
    return eval(repr(kinetics), {"__builtins__": {}}, context)


def _fit_autogenerated_node(family, node_label, reactions):
    """Fit one autogenerated node by RMG's tree-generation code path."""
    kinetics = _make_rule(
        (
            family.forward_recipe.actions,
            reactions,
            1000.0,
            1.0e5,
            node_label,
            [reaction.rank for reaction in reactions],
        )
    )
    if kinetics is None:
        raise ValueError("RMG could not fit the listed training reactions")
    return _persist_generated_kinetics(kinetics)


def run_autogenerated_oracle_positive_control(
    database_path: str | Path,
) -> dict[str, Any]:
    """Regenerate, persist, reload, and independently refit one small family."""
    database_path = Path(database_path).resolve()
    family_source = database_path / "input/kinetics/families" / ORACLE_CONTROL_FAMILY
    scratch_parent = (
        Path(__file__).resolve().parents[1] / "output/kmc-provenance/oracle-control"
    )
    scratch_parent.mkdir(parents=True, exist_ok=True)

    thermo_owner = RMGDatabase()
    thermo_owner.load_thermo(
        str(database_path / "input/thermo"),
        thermo_libraries=["primaryThermoLibrary"],
        depository=True,
    )

    def run_in_scratch(scratch: Path):
        def load_scratch_family():
            kinetics_database = KineticsDatabase()
            family = KineticsFamily(label=ORACLE_CONTROL_FAMILY)
            family.load(
                str(scratch),
                kinetics_database.local_context,
                kinetics_database.global_context,
                depository_labels=["training"],
            )
            return family

        generated = load_scratch_family()
        generated.clean_tree()
        generated.make_tree(thermo_database=thermo_owner.thermo, T=1000.0)
        generated.save(str(scratch))

        reloaded = load_scratch_family()
        training_map = _autogenerated_training_map(reloaded, thermo_owner.thermo, {})
        node_results = []
        for node_label, pairs in sorted(training_map.items()):
            stored_entries = reloaded.rules.entries.get(node_label, [])
            if not stored_entries or not pairs:
                continue
            reactions = [reaction for _, reaction in pairs]
            refit = _fit_autogenerated_node(reloaded, node_label, reactions)
            stored = stored_entries[0].data
            errors = [
                abs(
                    refit.get_rate_coefficient(temperature)
                    - stored.get_rate_coefficient(temperature)
                )
                / abs(stored.get_rate_coefficient(temperature))
                for temperature in DEFAULT_T_GRID
            ]
            node_results.append(
                {
                    "node": node_label,
                    "training_reaction_count": len(reactions),
                    "maximum_relative_error": max(errors),
                }
            )
        if not node_results:
            raise ValueError("positive-control regeneration produced no fitted nodes")
        maximum_error = max(item["maximum_relative_error"] for item in node_results)
        result = {
            "family": ORACLE_CONTROL_FAMILY,
            "source_node_count": len(node_results),
            "maximum_relative_error": maximum_error,
            "rate_matches": maximum_error <= RATE_REPRODUCTION_RTOL,
            "nodes": node_results,
        }
        if not result["rate_matches"]:
            raise ValueError(
                "fresh autogenerated rules do not reproduce after persistence: "
                f"maximum relative error {maximum_error:.12g}"
            )
        return result

    with tempfile.TemporaryDirectory(
        prefix=f"{ORACLE_CONTROL_FAMILY}-", dir=scratch_parent
    ) as scratch_name:
        scratch = Path(scratch_name)
        shutil.copytree(family_source, scratch, dirs_exist_ok=True)
        return run_in_scratch(scratch)


def _extract_git_tree(repository: Path, commit: str, prefix: str, destination: Path):
    """Extract one historical tree using only ``git show commit:path``."""
    paths = subprocess.check_output(
        ["git", "-C", str(repository), "ls-tree", "-r", "--name-only", commit, prefix],
        text=True,
    ).splitlines()
    if not paths:
        raise ValueError(f"no paths found at {commit}:{prefix}")
    for relative in paths:
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(
            subprocess.check_output(
                ["git", "-C", str(repository), "show", f"{commit}:{relative}"]
            )
        )


def _load_historical_thermo(path: Path):
    """Load the thermo inputs used by the historical generateTree script."""
    thermo = ThermoDatabase()
    thermo.depository = {}
    thermo.load_libraries(
        str(path / "libraries"), list(LEGACY_TREE_THERMO_LIBRARIES)
    )
    thermo.groups = {
        source.stem: ThermoGroups(label=source.stem).load(
            str(source), thermo.local_context, thermo.global_context
        )
        for source in sorted((path / "groups").glob("*.py"))
    }
    thermo.record_ring_generic_nodes()
    thermo.record_polycylic_generic_nodes()
    return thermo


def _load_scratch_family(path: Path, label: str):
    kinetics_database = KineticsDatabase()
    family = KineticsFamily(label=label)
    family.load(
        str(path),
        kinetics_database.local_context,
        kinetics_database.global_context,
        depository_labels=["training"],
    )
    return family


def _legacy_bm_fit(reactions, recipe):
    """Reproduce ArrheniusBM.fit_to_reactions before the N=1 switch."""
    w0_values = get_w0s(recipe, reactions)
    w0 = sum(w0_values) / len(w0_values)
    units = ("", "s^-1", "m^3/(mol*s)", "m^6/(mol^2*s)")
    order = len(reactions[0].reactants)
    if len(reactions) == 1:
        reaction = reactions[0]
        delta_h = reaction.get_enthalpy_of_reaction(1000.0)
        activation_energy = reaction.kinetics.Ea.value_si

        def residual(E0):
            potential = 2 * w0 * (2 * w0 + 2 * E0) / (2 * w0 - 2 * E0)
            return activation_energy - (w0 + delta_h / 2.0) * (
                potential - 2 * w0 + delta_h
            ) ** 2 / (potential**2 - (2 * w0) ** 2 + delta_h**2)

        if abs(delta_h) > 4 * w0 / 10.0:
            E0 = w0 / 10.0
        else:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", RuntimeWarning)
                E0 = fsolve(residual, w0 / 10.0)[0]
        fitted = ArrheniusBM(
            A=(reaction.kinetics.A.value_si, units[order]),
            n=reaction.kinetics.n.value_si,
            w0=(w0, "J/mol"),
            E0=(E0, "J/mol"),
            Tmin=reaction.kinetics.Tmin,
            Tmax=reaction.kinetics.Tmax,
        )
        return _persist_generated_kinetics(fitted)

    def model(inputs, lnA, n, E0):
        temperatures = inputs[:, 0]
        delta_h = inputs[:, 1]
        potential = 2 * w0 * (2 * w0 + 2 * E0) / (2 * w0 - 2 * E0)
        activation_energy = (w0 + delta_h / 2.0) * (
            potential - 2 * w0 + delta_h
        ) ** 2 / (potential**2 - (2 * w0) ** 2 + delta_h**2)
        activation_energy = np.where(delta_h < -4.0 * E0, 0.0, activation_energy)
        activation_energy = np.where(
            delta_h > 4.0 * E0, delta_h, activation_energy
        )
        return lnA + np.log(
            temperatures**n * np.exp(-activation_energy / (8.314 * temperatures))
        )

    inputs = []
    outputs = []
    sigmas = []
    for reaction in reactions:
        sigma = rank_accuracy_map[reaction.rank].value_si / 2.0
        for temperature in LEGACY_TEMPERATURE_GRID:
            inputs.append(
                [temperature, reaction.get_enthalpy_of_reaction(temperature)]
            )
            outputs.append(np.log(reaction.get_rate_coefficient(temperature)))
            sigmas.append(sigma / (8.314 * temperature))
    tolerance = 1.0e-8
    while True:
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", OptimizeWarning)
                parameters = curve_fit(
                    model,
                    np.array(inputs),
                    np.array(outputs),
                    sigma=sigmas,
                    p0=[1.0, 1.0, w0 / 10.0],
                    xtol=tolerance,
                    ftol=tolerance,
                )[0]
            break
        except RuntimeError:
            if tolerance >= 1.0:
                raise ValueError("legacy BM fit did not converge")
            tolerance *= 10.0
    fitted = ArrheniusBM(
        A=(np.exp(parameters[0]), units[order]),
        n=parameters[1],
        w0=(w0, "J/mol"),
        E0=(parameters[2], "J/mol"),
        Tmin=(min(LEGACY_TEMPERATURE_GRID), "K"),
        Tmax=(max(LEGACY_TEMPERATURE_GRID), "K"),
    )
    return _persist_generated_kinetics(fitted)


def _kinetics_reproduction(fitted, stored):
    fitted_rates = [
        fitted.get_rate_coefficient(temperature) for temperature in DEFAULT_T_GRID
    ]
    stored_rates = [
        stored.get_rate_coefficient(temperature) for temperature in DEFAULT_T_GRID
    ]
    errors = [
        abs(actual - expected) / abs(expected)
        for actual, expected in zip(fitted_rates, stored_rates)
    ]
    maximum_error = max(errors)
    return {
        "stored_rate": {"T": list(DEFAULT_T_GRID), "k": stored_rates},
        "refit_rate": {"T": list(DEFAULT_T_GRID), "k": fitted_rates},
        "maximum_relative_error": maximum_error,
        "rate_matches": maximum_error <= RATE_REPRODUCTION_RTOL,
    }


def run_legacy_rate_oracle(
    database_path: str | Path, live_thermo_database=None
) -> dict[str, Any]:
    """Numerically reproduce the six legacy autogenerated source nodes."""
    database_path = Path(database_path).resolve()
    if live_thermo_database is None:
        live_thermo_database = ThermoDatabase()
        live_thermo_database.load(
            str(database_path / "input/thermo"),
            libraries=["primaryThermoLibrary"],
            depository=True,
        )
    scratch_parent = (
        Path(__file__).resolve().parents[1] / "output/kmc-provenance/legacy-oracle"
    )
    scratch_parent.mkdir(parents=True, exist_ok=True)
    results = []
    control = None
    with tempfile.TemporaryDirectory(prefix="historical-", dir=scratch_parent) as name:
        scratch = Path(name)
        for commit in sorted({spec[0] for spec in LEGACY_NODE_SPECS}):
            _extract_git_tree(database_path, commit, "input/thermo", scratch / commit)
            families = sorted(
                {spec[1] for spec in LEGACY_NODE_SPECS if spec[0] == commit}
            )
            for family_label in families:
                _extract_git_tree(
                    database_path,
                    commit,
                    f"input/kinetics/families/{family_label}",
                    scratch / commit,
                )

        for commit in sorted({spec[0] for spec in LEGACY_NODE_SPECS}):
            base = scratch / commit
            historical_thermo = _load_historical_thermo(base / "input/thermo")
            for family_label in sorted(
                {spec[1] for spec in LEGACY_NODE_SPECS if spec[0] == commit}
            ):
                family_path = base / "input/kinetics/families" / family_label
                family = _load_scratch_family(family_path, family_label)
                mapping = _autogenerated_training_map(
                    family, historical_thermo, {}
                )
                live_mapping = None
                for _, _, node_label in (
                    spec
                    for spec in LEGACY_NODE_SPECS
                    if spec[0] == commit and spec[1] == family_label
                ):
                    pairs = mapping[node_label]
                    reactions = [reaction for _, reaction in pairs]
                    stored = family.rules.entries[node_label][0].data
                    reproduction = _kinetics_reproduction(
                        _legacy_bm_fit(reactions, family.forward_recipe.actions),
                        stored,
                    )
                    contributors = [
                        serialize_entry(
                            entry, "training reaction", family_label
                        )
                        for entry, _ in pairs
                    ]
                    result = {
                        "family": family_label,
                        "node": node_label,
                        "historical_commit": commit,
                        "resolution": f"RESOLVED:historical-{commit[:10]}",
                        "training_reaction_count": len(reactions),
                        "contributors": contributors,
                        "contains_5002_or_5003": any(
                            item["index"] in {5002, 5003} for item in contributors
                        ),
                        **reproduction,
                    }
                    if family_label == "Disproportionation" and len(reactions) == 8:
                        live_family = _load_scratch_family(family_path, family_label)
                        live_mapping = _autogenerated_training_map(
                            live_family, live_thermo_database, {}
                        )
                        live_reactions = [
                            reaction for _, reaction in live_mapping[node_label]
                        ]
                        live_fit = _legacy_bm_fit(
                            live_reactions, live_family.forward_recipe.actions
                        )
                        result["historical_training_live_thermo_relative_error"] = (
                            _kinetics_reproduction(live_fit, stored)[
                                "maximum_relative_error"
                            ]
                        )
                        result["change_that_reproduces"] = (
                            "historical thermo files and generateTree thermo-library "
                            "order; the contributor set is unchanged"
                        )
                    elif len(reactions) == 1:
                        result["change_that_reproduces"] = (
                            "pre-d012688769 ArrheniusBM.fit_to_reactions N=1 path"
                        )
                    else:
                        result["change_that_reproduces"] = (
                            "historical N=5 training set"
                        )
                    results.append(result)

                    if family_label == "R_Recombination" and len(reactions) == 5:
                        original_A = reactions[0].kinetics.A.value_si
                        reactions[0].kinetics.A.value_si = original_A * 2.0
                        try:
                            perturbed = _kinetics_reproduction(
                                _legacy_bm_fit(
                                    reactions, family.forward_recipe.actions
                                ),
                                stored,
                            )
                        finally:
                            reactions[0].kinetics.A.value_si = original_A
                        control = {
                            "family": family_label,
                            "node": node_label,
                            "contributor": contributors[0],
                            "factor": 2.0,
                            **perturbed,
                        }
    if control is None:
        raise ValueError("legacy oracle did not execute its perturbation control")
    return {
        "single_reaction_switch_commit": LEGACY_SINGLE_REACTION_SWITCH_COMMIT,
        "fit_function": "legacy ArrheniusBM.fit_to_reactions",
        "temperature_grid_K": list(LEGACY_TEMPERATURE_GRID),
        "thermo_libraries": list(LEGACY_TREE_THERMO_LIBRARIES),
        "extraction_method": "git show <commit>:<path>",
        "source_node_count": len(results),
        "rate_matches": all(item["rate_matches"] for item in results),
        "nodes": sorted(results, key=lambda item: (item["family"], item["node"])),
        "perturbation_control": control,
    }


def _run_legacy_rate_oracle_isolated(database_path: Path) -> dict[str, Any]:
    """Run the memory-heavy historical loads in a short-lived interpreter."""
    repository = Path(__file__).resolve().parents[2]
    environment = os.environ.copy()
    environment["PYTHONPATH"] = os.pathsep.join(
        filter(None, [str(repository), environment.get("PYTHONPATH", "")])
    )
    program = (
        "import json,sys; "
        "from rmgpy.kmc.provenance import run_legacy_rate_oracle; "
        "print(json.dumps(run_legacy_rate_oracle(sys.argv[1]), sort_keys=True))"
    )
    output = subprocess.check_output(
        [sys.executable, "-c", program, str(database_path)],
        text=True,
        env=environment,
    )
    return json.loads(output)


def _run_positive_control_isolated(database_path: Path) -> dict[str, Any]:
    """Run scratch tree generation without retaining its database objects."""
    repository = Path(__file__).resolve().parents[2]
    environment = os.environ.copy()
    environment["PYTHONPATH"] = os.pathsep.join(
        filter(None, [str(repository), environment.get("PYTHONPATH", "")])
    )
    program = (
        "import json,sys; "
        "from rmgpy.kmc.provenance import "
        "run_autogenerated_oracle_positive_control; "
        "print(json.dumps(run_autogenerated_oracle_positive_control(sys.argv[1]), "
        "sort_keys=True))"
    )
    output = subprocess.check_output(
        [sys.executable, "-c", program, str(database_path)],
        text=True,
        env=environment,
    )
    return json.loads(output)


def _text_values(value: Any):
    if value is None:
        return
    if isinstance(value, dict):
        for item in value.values():
            yield from _text_values(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            yield from _text_values(item)
    else:
        yield str(value)


def entry_flag_terms(entry) -> list[str]:
    """Return fixed-list terms found in an entry's descriptions or reference."""
    fields = [
        getattr(entry, "short_desc", ""),
        getattr(entry, "long_desc", ""),
    ]
    reference = getattr(entry, "reference", None)
    if reference is not None:
        fields.append(vars(reference) if hasattr(reference, "__dict__") else reference)
    haystack = "\n".join(_text_values(fields)).casefold()
    return [term for term in FLAG_TERMS if term.casefold() in haystack]


def _json_value(value: Any) -> Any:
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, (list, tuple)):
        return [_json_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_value(item) for key, item in value.items()}
    return str(value)


def serialize_entry(
    entry, source_kind: str, family: str, *, weight: float | None = None
) -> dict[str, Any]:
    """Serialize the source metadata RMG loaded for one database entry."""
    reference = getattr(entry, "reference", None)
    reference_data = None
    if reference is not None:
        reference_data = {"type": type(reference).__name__}
        if hasattr(reference, "__dict__"):
            reference_data.update(
                {
                    key: _json_value(value)
                    for key, value in vars(reference).items()
                    if not key.startswith("_")
                }
            )
        else:
            reference_data["value"] = str(reference)
    terms = entry_flag_terms(entry)
    return {
        "family": family,
        "source_kind": source_kind,
        "index": getattr(entry, "index", None),
        "label": getattr(entry, "label", ""),
        "rank": getattr(entry, "rank", None),
        "weight": None if weight is None else float(weight),
        "short_desc": getattr(entry, "short_desc", ""),
        "long_desc": getattr(entry, "long_desc", ""),
        "reference_type": getattr(entry, "reference_type", ""),
        "reference": reference_data,
        "flag_terms": terms,
        "flagged": bool(terms),
    }


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")


def write_content_addressed_audit(
    audit: dict[str, Any], output_directory: str | Path
) -> Path:
    payload = canonical_json_bytes(audit)
    digest = hashlib.sha256(payload).hexdigest()
    path = Path(output_directory) / f"{digest}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return path


def _entry_key(entry: dict[str, Any]) -> tuple[Any, ...]:
    return (
        entry["family"],
        entry["source_kind"],
        entry["index"],
        entry["label"],
    )


def _record_key(record) -> tuple[Any, ...]:
    getter = (
        record.get if isinstance(record, dict) else lambda key: getattr(record, key)
    )
    return (
        getter("family"),
        getter("template"),
        getter("site_type"),
        getter("orientation"),
        float(getter("raw_path_degeneracy")),
        tuple(getter("reactant_graphs")),
        tuple(getter("product_graphs")),
    )


def _selected_autogenerated_entry(family, template):
    """Apply the autogenerated-tree node selection using loaded rule objects."""
    entry = family.rules.get_rule(template)
    if entry is None:
        raise ValueError("autogenerated template has no rate-rule node")
    while entry.parent is not None:
        parent = entry.parent
        parent_uncertainty = parent.data.uncertainty
        entry_uncertainty = entry.data.uncertainty
        parent_error = abs(
            parent_uncertainty.data_mean
            + parent_uncertainty.mu
            - entry_uncertainty.data_mean
        ) + math.sqrt(2.0 * parent_uncertainty.var / math.pi)
        entry_error = abs(entry_uncertainty.mu) + math.sqrt(
            2.0 * entry_uncertainty.var / math.pi
        )
        if entry_error <= parent_error:
            break
        entry = parent
    return entry


def _autogenerated_training_map(family, thermo_database, cache):
    cache_key = (family.label, "all-node-training-contributors")
    if cache_key in cache:
        return cache[cache_key]

    depository_entries = list(family.get_training_depository().entries.values())
    training_reactions = family.get_training_set(
        thermo_database=thermo_database,
        remove_degeneracy=True,
        estimate_thermo=True,
        # Match make_tree(), which fits the persisted autogenerated rules from
        # get_reaction_matches(remove_degeneracy=True, get_reverse=True).
        fix_labels=False,
        get_reverse=True,
        rxns_with_kinetics_only=False,
    )
    source_entries = depository_entries + (
        depository_entries if family.own_reverse else []
    )
    if len(training_reactions) != len(source_entries):
        raise ValueError(
            "RMG training-set orientation did not preserve entry correspondence"
        )
    entry_by_reaction = {
        id(reaction): entry
        for reaction, entry in zip(training_reactions, source_entries)
    }
    matches = family.get_reaction_matches(
        rxns=training_reactions,
        exact_matches_only=False,
    )
    result = {}
    for label, reactions in matches.items():
        pairs = [
            (entry_by_reaction[id(reaction)], reaction)
            for reaction in reactions
            if type(entry_by_reaction[id(reaction)].data) is not KineticsModel
        ]
        pairs.sort(key=lambda pair: (pair[0].index, pair[0].label))
        result[label] = pairs
    cache[cache_key] = result
    return result


def _autogenerated_training_contributors(
    family, node, thermo_database, contributor_cache
):
    pairs = _autogenerated_training_map(family, thermo_database, contributor_cache).get(
        node.label, []
    )
    unique = {}
    for entry, _ in pairs:
        unique[(entry.index, entry.label)] = entry
    return [unique[key] for key in sorted(unique)]


def _deduplicate_contributors(contributors):
    unique = {}
    for contributor in contributors:
        unique[_entry_key(contributor)] = contributor
    return [
        unique[key]
        for key in sorted(unique, key=lambda item: tuple(str(x) for x in item))
    ]


def _trace_rate_source(compiler, reaction, contributor_cache) -> dict[str, Any]:
    source_reaction = getattr(reaction, "source_reaction", reaction)
    family_label = getattr(source_reaction, "family", "")
    transform = (
        "reverse from RMG gas-phase Kc"
        if source_reaction is not reaction
        else "forward RMG family estimate"
    )
    family = compiler.kinetics_database.families.get(family_label)
    if family is None:
        return {
            "resolution": "UNRESOLVED",
            "origin": "UNRESOLVED",
            "reason": f"kinetics family {family_label!r} is not loaded",
            "node": None,
            "rate_transform": transform,
            "contributors": [],
        }

    attached = getattr(source_reaction, "kinetics", None)
    if attached is not None:
        entry = getattr(source_reaction, "entry", None)
        library = getattr(source_reaction, "library", None)
        if entry is None or library is None:
            return {
                "resolution": "UNRESOLVED",
                "origin": "UNRESOLVED",
                "reason": "attached kinetics has no structured library entry",
                "node": None,
                "rate_transform": transform,
                "contributors": [],
            }
        contributor = serialize_entry(entry, "library", str(library.label))
        return {
            "resolution": "RESOLVED",
            "origin": "library",
            "reason": None,
            "node": entry.label,
            "rate_transform": transform,
            "contributors": [contributor],
        }

    try:
        _, source, entry, _ = family.get_kinetics(
            source_reaction,
            template_labels=source_reaction.template,
            degeneracy=source_reaction.degeneracy,
            return_all_kinetics=False,
        )
    except Exception as error:
        return {
            "resolution": "UNRESOLVED",
            "origin": "UNRESOLVED",
            "reason": f"RMG kinetics resolution failed: {error}",
            "node": None,
            "rate_transform": transform,
            "contributors": [],
        }

    if source != "rate rules":
        if entry is None:
            return {
                "resolution": "UNRESOLVED",
                "origin": "UNRESOLVED",
                "reason": "depository match did not expose its database entry",
                "node": None,
                "rate_transform": transform,
                "contributors": [],
            }
        contributor = serialize_entry(entry, "training reaction", family_label)
        return {
            "resolution": "RESOLVED",
            "origin": "exact training match",
            "reason": None,
            "node": entry.label,
            "rate_transform": transform,
            "contributors": [contributor],
        }

    template = family.retrieve_template(source_reaction.template)
    if family.auto_generated:
        try:
            node_entry = _selected_autogenerated_entry(family, template)
            contributors = [
                serialize_entry(node_entry, "autogenerated rate rule", family_label)
            ]
            contributors.extend(
                serialize_entry(item, "training reaction", family_label)
                for item in _autogenerated_training_contributors(
                    family,
                    family.groups.entries[node_entry.label],
                    compiler.thermo_database,
                    contributor_cache,
                )
            )
        except Exception as error:
            return {
                "resolution": "UNRESOLVED",
                "origin": "UNRESOLVED",
                "reason": f"autogenerated contributor resolution failed: {error}",
                "node": getattr(entry, "label", None),
                "rate_transform": transform,
                "contributors": [],
            }
        return {
            "resolution": "RESOLVED",
            "origin": "autogenerated node",
            "reason": None,
            "node": node_entry.label,
            "rate_transform": transform,
            "contributors": _deduplicate_contributors(contributors),
        }

    try:
        rules, training = family.get_sources_for_template(template)
        contributors = []
        for rule_entry, weight in rules:
            contributors.append(
                serialize_entry(rule_entry, "rate rule", family_label, weight=weight)
            )
            try:
                _, training_entry = family.retrieve_original_entry(rule_entry.label)
            except Exception:
                training_entry = None
            if training_entry is not None:
                contributors.append(
                    serialize_entry(
                        training_entry,
                        "training reaction",
                        family_label,
                        weight=weight,
                    )
                )
        for rule_entry, training_entry, weight in training:
            contributors.append(
                serialize_entry(
                    rule_entry, "generated rate rule", family_label, weight=weight
                )
            )
            contributors.append(
                serialize_entry(
                    training_entry,
                    "training reaction",
                    family_label,
                    weight=weight,
                )
            )
        contributors = _deduplicate_contributors(contributors)
    except Exception as error:
        return {
            "resolution": "UNRESOLVED",
            "origin": "UNRESOLVED",
            "reason": f"rate-rule contributor resolution failed: {error}",
            "node": getattr(entry, "label", None),
            "rate_transform": transform,
            "contributors": [],
        }

    rule_contributors = [
        item
        for item in contributors
        if item["source_kind"] in {"rate rule", "generated rate rule"}
    ]
    if entry is not None or len(rule_contributors) == 1:
        origin = "rate rule node"
        node = entry.label if entry is not None else rule_contributors[0]["label"]
    else:
        origin = "averaged node"
        node = None
    return {
        "resolution": "RESOLVED",
        "origin": origin,
        "reason": None,
        "node": node,
        "rate_transform": transform,
        "contributors": contributors,
    }


class _TracingCompiler(EventSetCompiler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.traces = []
        self._contributor_cache = {}
        self._trace_cache = {}

    def _record(self, proxy, reaction, provenance, orientation="as_generated"):
        record = super()._record(proxy, reaction, provenance, orientation)
        source_reaction = getattr(reaction, "source_reaction", reaction)
        cache_key = None
        if record.rate_source.get("source") == "rate rules":
            cache_key = (
                record.family,
                tuple(getattr(source_reaction, "template", ())),
                source_reaction is not reaction,
            )
        if cache_key is not None and cache_key in self._trace_cache:
            trace = deepcopy(self._trace_cache[cache_key])
        else:
            trace = _trace_rate_source(self, reaction, self._contributor_cache)
            if cache_key is not None:
                self._trace_cache[cache_key] = deepcopy(trace)
        self.traces.append((_record_key(record), trace, reaction))
        return record


@dataclass
class AuditBuild:
    audit: dict[str, Any]
    artifact: dict[str, Any]
    audit_path: Path | None
    event_set_path: Path
    compiler: _TracingCompiler
    contexts: dict[str, tuple[Any, dict[str, Any]]]
    source_reproductions: dict[tuple[str, str, str], dict[str, Any]]
    historical_reproductions: dict[tuple[str, str, str], dict[str, Any]]


def _git_head(path: Path) -> str:
    return subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
    ).strip()


def _git_blame_entry_kinetics_commit(repository: Path, path: Path, label: str) -> str:
    lines = path.read_text().splitlines()
    label_text = f'label = "{label}",'
    matches = [index for index, line in enumerate(lines) if label_text in line]
    if len(matches) != 1:
        raise ValueError(
            f"expected one {label_text!r} line in {path}, found {len(matches)}"
        )
    kinetics_line = None
    for index in range(matches[0] + 1, len(lines)):
        if lines[index].startswith("entry("):
            break
        if lines[index].lstrip().startswith("kinetics ="):
            kinetics_line = index + 1
            break
    if kinetics_line is None:
        raise ValueError(f"entry {label!r} in {path} has no kinetics line")
    relative_path = path.relative_to(repository)
    blame = subprocess.check_output(
        [
            "git",
            "-C",
            str(repository),
            "blame",
            "--porcelain",
            f"-L{kinetics_line},{kinetics_line}",
            "--",
            str(relative_path),
        ],
        text=True,
    )
    return blame.splitlines()[0].split()[0]


def _git_entry_addition_commit(repository: Path, path: Path, label: str) -> str:
    relative_path = path.relative_to(repository)
    commits = subprocess.check_output(
        [
            "git",
            "-C",
            str(repository),
            "log",
            "--reverse",
            "--format=%H",
            "-S",
            f'label = "{label}",',
            "--",
            str(relative_path),
        ],
        text=True,
    ).splitlines()
    if not commits:
        raise ValueError(f"could not find addition commit for {label!r} in {path}")
    return commits[0]


def _entry_present_at_commit(
    repository: Path, commit: str, path: Path, label: str
) -> bool:
    relative_path = path.relative_to(repository)
    try:
        historical = subprocess.check_output(
            [
                "git",
                "-C",
                str(repository),
                "show",
                f"{commit}:{relative_path}",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return False
    return f'label = "{label}",' in historical


def build_audit(database_path: str | Path, output_directory: str | Path) -> AuditBuild:
    """Compile the exact PS corpus and write its canonical provenance audit."""
    database_path = Path(database_path).resolve()
    output_directory = Path(output_directory).resolve()
    legacy_oracle = _run_legacy_rate_oracle_isolated(database_path)
    positive_control = _run_positive_control_isolated(database_path)
    family_root = database_path / "input/kinetics/families"
    family_universe = sorted(
        path.name for path in family_root.iterdir() if (path / "groups.py").is_file()
    )
    database = RMGDatabase()
    database.load_kinetics(
        str(database_path / "input/kinetics"),
        reaction_libraries=[],
        seed_mechanisms=None,
        kinetics_families=list(PS_FAMILY_CANDIDATES),
        kinetics_depositories=["training"],
    )
    database.load_thermo(
        str(database_path / "input/thermo"),
        thermo_libraries=["primaryThermoLibrary"],
        depository=True,
    )
    proxies = ps_proxy_set(PS_PROXY_UNITS)
    active, excluded, reactions = EventSetCompiler.discover_family_reactions(
        database.kinetics,
        proxies,
        PS_FAMILY_CANDIDATES,
        family_universe=family_universe,
    )
    compiler = _TracingCompiler(
        database.kinetics,
        proxies,
        active,
        excluded_families=excluded,
        database_path=database_path,
        thermo_database=database.thermo,
        reaction_cache=reactions,
    )
    event_set_path, artifact = compiler.write_artifact(output_directory / "event-set")
    validate_artifact(artifact)

    trace_queues = defaultdict(deque)
    for key, trace, reaction in compiler.traces:
        trace_queues[key].append((trace, reaction))
    audit_records = []
    contexts = {}
    for record in artifact["records"]:
        queue = trace_queues[_record_key(record)]
        if queue:
            trace, reaction = queue.popleft()
        else:
            reaction = None
            trace = {
                "resolution": "UNRESOLVED",
                "origin": "UNRESOLVED",
                "reason": "compiled record did not match a regenerated reaction",
                "node": None,
                "rate_transform": record["rate_source"].get("reference"),
                "contributors": [],
            }
        flag_terms = sorted(
            {
                term
                for contributor in trace["contributors"]
                for term in contributor["flag_terms"]
            },
            key=lambda term: FLAG_TERMS.index(term),
        )
        audit_record = {
            "event_id": record["event_id"],
            "family": record["family"],
            "template_labels": (
                record["template"].split(";") if record["template"] else []
            ),
            **trace,
            "flag_terms": flag_terms,
            "flagged": bool(flag_terms),
        }
        audit_records.append(audit_record)
        contexts[record["event_id"]] = (reaction, trace)
    leftovers = sum(len(queue) for queue in trace_queues.values())
    if leftovers:
        raise ValueError(f"{leftovers} regenerated reaction traces were not audited")

    audit = {
        "schema_version": "kmc_rate_provenance/0.4",
        "event_set_sha256": event_set_path.stem,
        "rmgpy_head": _git_head(Path(__file__).resolve().parents[2]),
        "rmg_database_commit": _git_head(database_path),
        "flag_terms": list(FLAG_TERMS),
        "refit_oracle": {
            "generation_path": [
                "KineticsFamily.make_tree",
                "KineticsFamily.get_reaction_matches(remove_degeneracy=True, get_reverse=True)",
                "KineticsFamily.make_bm_rules_from_template_rxn_map",
                "rmgpy.data.kinetics.family._make_rule",
            ],
            "refit_function": "rmgpy.data.kinetics.family._make_rule",
            "same_fit_function_as_tree_generation": True,
            "multi_reaction_fit": "ArrheniusBM.fit_to_reactions",
            "single_reaction_or_negative_E0_fallback": "average_kinetics",
            "thermo_path": "KineticsFamily.get_training_set with the loaded RMG ThermoDatabase (primaryThermoLibrary plus RMG estimation) assigns reactant and product thermo used for dHrxn",
            "reaction_selection": {
                "remove_degeneracy": True,
                "estimate_thermo": True,
                "fix_labels": False,
                "get_reverse": True,
                "exact_matches_only": False,
                "rxns_with_kinetics_only": False,
            },
            "rank_convention": "Reaction.rank from each training depository Entry; _make_rule applies RMG's rank weighting",
            "Tref_K": 1000.0,
            "fmax": 100000.0,
            "evaluation_temperatures_K": list(DEFAULT_T_GRID),
            "rate_units": "RMG SI from KineticsModel.get_rate_coefficient; each event-set k_table carries its reaction-order unit",
            "persistence_convention": "refitted kinetics is round-tripped through its RMG repr, matching rules.py save/load precision before rate evaluation",
            "positive_control": positive_control,
        },
        "records": audit_records,
    }
    build = AuditBuild(
        audit=audit,
        artifact=artifact,
        audit_path=None,
        event_set_path=event_set_path,
        compiler=compiler,
        contexts=contexts,
        source_reproductions={},
        historical_reproductions={},
    )
    build.source_reproductions = reproduce_all_source_nodes(build)
    current_diagnoses = diagnose_stale_source_nodes(build, database_path)
    audit["legacy_rate_oracle"] = legacy_oracle
    by_legacy_node = {
        (item["family"], item["node"]): item for item in legacy_oracle["nodes"]
    }
    for (family_label, node_label), historical in by_legacy_node.items():
        live_stored = database.kinetics.families[family_label].rules.entries[
            node_label
        ][0].data
        live_rates = [
            live_stored.get_rate_coefficient(temperature)
            for temperature in DEFAULT_T_GRID
        ]
        historical_rates = historical["stored_rate"]["k"]
        live_errors = [
            abs(live - old) / abs(live)
            for live, old in zip(live_rates, historical_rates)
        ]
        historical["live_stored_rate"] = {
            "T": list(DEFAULT_T_GRID),
            "k": live_rates,
        }
        historical["historical_live_stored_relative_error"] = max(live_errors)
        historical["live_stored_rate_matches"] = max(live_errors) <= (
            RATE_REPRODUCTION_RTOL
        )
        historical["rate_matches"] = (
            historical["rate_matches"] and historical["live_stored_rate_matches"]
        )
    legacy_oracle["rate_matches"] = all(
        item["rate_matches"] for item in legacy_oracle["nodes"]
    )
    for source, reproduction in build.source_reproductions.items():
        legacy = by_legacy_node.get((source[0], source[2]))
        if legacy is not None:
            build.historical_reproductions[source] = legacy
    diagnoses = {
        (item["family"], item["node"]): item for item in current_diagnoses
    }
    historical_nodes = []
    for source, historical in sorted(
        build.historical_reproductions.items(), key=lambda item: item[0]
    ):
        if not historical["rate_matches"]:
            continue
        item = deepcopy(historical)
        diagnosis = diagnoses[(source[0], source[2])]
        item.update(
            {
                "original_origin": source[1],
                "current_maximum_relative_error": diagnosis[
                    "maximum_relative_error"
                ],
                "dependent_event_ids": diagnosis["dependent_event_ids"],
                "flagged_contributor_present": any(
                    contributor["flagged"]
                    for contributor in historical["contributors"]
                ),
            }
        )
        historical_nodes.append(item)
    audit["historical_nodes"] = historical_nodes
    audit["stale_nodes"] = [
        item
        for item in current_diagnoses
        if not by_legacy_node.get((item["family"], item["node"]), {}).get(
            "rate_matches", False
        )
    ]
    qualify_stale_source_records(
        audit_records, build.source_reproductions, build.historical_reproductions
    )
    verify_stale_source_classification(
        audit_records, build.source_reproductions, build.historical_reproductions
    )
    build.audit_path = write_content_addressed_audit(audit, output_directory)
    return build


def _contributor_keys(trace):
    return {_entry_key(item) for item in trace["contributors"]}


def qualify_stale_source_records(
    audit_records, source_reproductions, historical_reproductions=None
) -> None:
    """Mark every record that depends on a non-reproducing source node."""
    historical_reproductions = historical_reproductions or {}
    by_event_id = {record["event_id"]: record for record in audit_records}
    for source, reproduction in source_reproductions.items():
        if reproduction["rate_matches"]:
            continue
        _, original_origin, node = source
        historical = historical_reproductions.get(source)
        for event_id in reproduction["dependent_event_ids"]:
            record = by_event_id[event_id]
            details = reproduction["records"][event_id]
            if historical is not None and historical["rate_matches"]:
                historical_contributors = deepcopy(historical["contributors"])
                historical_flag_terms = sorted(
                    {
                        term
                        for contributor in historical_contributors
                        for term in contributor["flag_terms"]
                    },
                    key=lambda term: FLAG_TERMS.index(term),
                )
                record.update(
                    {
                        "resolution": historical["resolution"],
                        "origin": "historical autogenerated node",
                        "original_origin": original_origin,
                        "reason": (
                            "stored node is reproduced by the historical RMG "
                            f"fit path at {historical['historical_commit']}"
                        ),
                        "node": node,
                        "current_contributors": record["contributors"],
                        "current_flag_terms": record["flag_terms"],
                        "current_flagged": record["flagged"],
                        "contributors": historical_contributors,
                        "flag_terms": historical_flag_terms,
                        "flagged": bool(historical_flag_terms),
                        "current_refit_rate": details["refit_rate"],
                        "current_relative_error": details["relative_error"],
                        "historical_refit_rate": historical["refit_rate"],
                        "historical_relative_error": historical[
                            "maximum_relative_error"
                        ],
                        "historical_commit": historical["historical_commit"],
                    }
                )
                continue
            record.update(
                {
                    "resolution": "UNRESOLVED:stale-node",
                    "origin": "UNRESOLVED:stale-node",
                    "original_origin": original_origin,
                    "reason": (
                        "listed contributors do not reproduce the stored rate "
                        f"within relative tolerance {RATE_REPRODUCTION_RTOL:g}"
                    ),
                    "node": node,
                    "stored_rate": details["stored_rate"],
                    "refit_rate": details["refit_rate"],
                    "relative_error": details["relative_error"],
                    "stale_node_diagnosis": reproduction.get("diagnosis"),
                }
            )


def verify_stale_source_classification(
    audit_records, source_reproductions, historical_reproductions=None
) -> None:
    """Require exhaustive reproduction results and correct stale-node labels."""
    historical_reproductions = historical_reproductions or {}
    by_event_id = {record["event_id"]: record for record in audit_records}
    audited_dependencies = defaultdict(set)
    for record in audit_records:
        if record["node"] is None or not record["contributors"]:
            continue
        original_origin = record.get("original_origin", record["origin"])
        source = (record["family"], original_origin, record["node"])
        audited_dependencies[source].add(record["event_id"])
    audited_sources = set(audited_dependencies)
    reproduced_sources = set(source_reproductions)
    if audited_sources != reproduced_sources:
        missing = sorted(audited_sources - reproduced_sources, key=str)
        extra = sorted(reproduced_sources - audited_sources, key=str)
        raise ValueError(
            f"source reproduction coverage differs: missing={missing}, extra={extra}"
        )

    for source, reproduction in source_reproductions.items():
        reproduced_dependencies = set(reproduction["dependent_event_ids"])
        if reproduced_dependencies != audited_dependencies[source]:
            raise ValueError(f"dependent-record coverage differs for source {source}")
        for event_id in reproduction["dependent_event_ids"]:
            record = by_event_id[event_id]
            if reproduction["rate_matches"]:
                if record["resolution"] == "UNRESOLVED:stale-node":
                    raise ValueError("reproducing source was labelled stale")
                continue
            historical = historical_reproductions.get(source)
            if historical is not None and historical["rate_matches"]:
                if (
                    record["resolution"] != historical["resolution"]
                    or record["origin"] != "historical autogenerated node"
                ):
                    raise ValueError(
                        f"historically reproducing source for {event_id} has "
                        "the wrong resolution"
                    )
                if _contributor_keys(record) != {
                    _entry_key(item) for item in historical["contributors"]
                }:
                    raise ValueError(
                        f"historical contributor set for {event_id} differs "
                        "from the reproducing oracle"
                    )
                expected_terms = sorted(
                    {
                        term
                        for contributor in record["contributors"]
                        for term in contributor["flag_terms"]
                    },
                    key=lambda term: FLAG_TERMS.index(term),
                )
                if (
                    record["flag_terms"] != expected_terms
                    or record["flagged"] != bool(expected_terms)
                ):
                    raise ValueError(
                        f"historical flags for {event_id} differ from its "
                        "effective contributors"
                    )
                continue
            if (
                record["resolution"] != "UNRESOLVED:stale-node"
                or record["origin"] != "UNRESOLVED:stale-node"
            ):
                raise ValueError(
                    f"non-reproducing source for {event_id} is not labelled "
                    "UNRESOLVED:stale-node"
                )
            details = reproduction["records"][event_id]
            for field in ("stored_rate", "refit_rate", "relative_error"):
                if record.get(field) != details[field]:
                    raise ValueError(f"stale record {event_id} has wrong {field}")


def _find_training_entry(family, contributor):
    entry = family.get_training_depository().entries.get(contributor["index"])
    if entry is None or entry.label != contributor["label"]:
        raise ValueError("listed training reaction does not resolve in RMG")
    return entry


def _filtered_rule_estimate(family, source_reaction, listed):
    allowed = {
        (item["index"], item["label"])
        for item in listed["contributors"]
        if item["source_kind"] in {"rate rule", "generated rate rule"}
    }
    if not allowed:
        raise ValueError("listed trace has no rate-rule contributor")
    original_entries = family.rules.entries
    filtered_entries = type(original_entries)()
    for label, entries in original_entries.items():
        retained = [entry for entry in entries if (entry.index, entry.label) in allowed]
        if retained:
            filtered_entries[label] = retained
    family.rules.entries = filtered_entries
    try:
        template = family.retrieve_template(source_reaction.template)
        kinetics, _ = family.rules.estimate_kinetics(
            template, source_reaction.degeneracy
        )
    finally:
        family.rules.entries = original_entries
    return kinetics


def _autogenerated_estimate(build, family, source_reaction, listed):
    node_label = listed["node"]
    training_map = _autogenerated_training_map(
        family,
        build.compiler.thermo_database,
        build.compiler._contributor_cache,
    )
    allowed = {
        (item["index"], item["label"])
        for item in listed["contributors"]
        if item["source_kind"] == "training reaction"
    }
    reactions = [
        reaction
        for entry, reaction in training_map.get(node_label, [])
        if (entry.index, entry.label) in allowed
    ]
    if not reactions:
        raise ValueError("listed trace has no fitted training reactions")
    kinetics = _fit_autogenerated_node(family, node_label, reactions)
    kinetics.A.value_si *= source_reaction.degeneracy
    return kinetics


def _kinetics_from_listed_contributors(build, reaction, listed):
    source_reaction = getattr(reaction, "source_reaction", reaction)
    family = build.compiler.kinetics_database.families[source_reaction.family]
    origin = listed["origin"]
    if origin == "exact training match":
        training = [
            item
            for item in listed["contributors"]
            if item["source_kind"] == "training reaction"
        ]
        if len(training) != 1:
            raise ValueError("exact training trace must list one training reaction")
        kinetics = deepcopy(_find_training_entry(family, training[0]).data)
        kinetics.A.value_si *= source_reaction.degeneracy
        return kinetics
    if origin == "library":
        entry = getattr(source_reaction, "entry", None)
        if entry is None:
            raise ValueError("library trace has no live RMG entry")
        expected = serialize_entry(entry, "library", str(source_reaction.library.label))
        if _entry_key(expected) not in _contributor_keys(listed):
            raise ValueError("listed library entry does not match RMG")
        return deepcopy(entry.data)
    if origin == "autogenerated node":
        return _autogenerated_estimate(build, family, source_reaction, listed)
    if origin in {"rate rule node", "averaged node"}:
        return _filtered_rule_estimate(family, source_reaction, listed)
    raise ValueError(f"cannot recompute unresolved origin {origin!r}")


def _rate_table_from_listed_contributors(build, reaction, listed):
    source_reaction = getattr(reaction, "source_reaction", reaction)
    kinetics = _kinetics_from_listed_contributors(build, reaction, listed)
    previous = getattr(source_reaction, "kinetics", None)
    source_reaction.kinetics = kinetics
    try:
        table, _ = build.compiler._rate_table(reaction)
    finally:
        source_reaction.kinetics = previous
    return table


def _reproduction_details(build: AuditBuild, audit_record) -> dict[str, Any]:
    event_id = audit_record["event_id"]
    reaction, runtime_trace = build.contexts[event_id]
    stored = next(
        record["k_table"]
        for record in build.artifact["records"]
        if record["event_id"] == event_id
    )
    if reaction is None or stored is None:
        return {
            "stored_rate": stored,
            "refit_rate": None,
            "relative_error": None,
            "rate_matches": False,
            "error": "record has no recomputable rate table",
        }
    if _contributor_keys(audit_record) != _contributor_keys(runtime_trace):
        return {
            "stored_rate": stored,
            "refit_rate": None,
            "relative_error": None,
            "rate_matches": False,
            "error": "listed contributor set is incomplete or contains extras",
        }
    try:
        refit = _rate_table_from_listed_contributors(build, reaction, audit_record)
    except Exception as error:
        return {
            "stored_rate": stored,
            "refit_rate": None,
            "relative_error": None,
            "rate_matches": False,
            "error": str(error),
        }
    if (
        refit is None
        or refit["T"] != stored["T"]
        or len(refit["k"]) != len(stored["k"])
    ):
        return {
            "stored_rate": stored,
            "refit_rate": refit,
            "relative_error": None,
            "rate_matches": False,
            "error": "refit and stored rate grids differ",
        }
    relative_errors = [
        (
            abs(actual - expected) / abs(expected)
            if expected != 0.0
            else (0.0 if actual == 0.0 else None)
        )
        for actual, expected in zip(refit["k"], stored["k"])
    ]
    finite_errors = [error for error in relative_errors if error is not None]
    maximum_error = max(finite_errors) if finite_errors else None
    rate_matches = all(
        error is not None and error <= RATE_REPRODUCTION_RTOL
        for error in relative_errors
    )
    return {
        "stored_rate": stored,
        "refit_rate": refit,
        "relative_error": maximum_error,
        "rate_matches": rate_matches,
        "error": None if rate_matches else "refit does not reproduce stored rate",
    }


def reproduce_all_source_nodes(
    build: AuditBuild,
) -> dict[tuple[str, str, str], dict[str, Any]]:
    """Reproduce every distinct named source node in the audit."""
    dependent_records = defaultdict(list)
    for record in build.audit["records"]:
        if (
            record["resolution"] == "RESOLVED"
            and record["node"] is not None
            and record["contributors"]
        ):
            key = (record["family"], record["origin"], record["node"])
            dependent_records[key].append(record)

    results = {}
    for source, records in sorted(dependent_records.items(), key=lambda item: item[0]):
        record_details = {
            record["event_id"]: _reproduction_details(build, record)
            for record in records
        }
        rate_matches = all(
            details["rate_matches"] for details in record_details.values()
        )
        relative_errors = [
            details["relative_error"]
            for details in record_details.values()
            if details["relative_error"] is not None
        ]
        errors = sorted(
            {
                details["error"]
                for details in record_details.values()
                if details["error"] is not None
            }
        )
        results[source] = {
            "family": source[0],
            "origin": source[1],
            "node": source[2],
            "representative_event_id": records[0]["event_id"],
            "dependent_event_ids": [record["event_id"] for record in records],
            "rate_matches": rate_matches,
            "relative_error": max(relative_errors) if relative_errors else None,
            "error": "; ".join(errors) if errors else None,
            "records": record_details,
        }
    return results


def diagnose_stale_source_nodes(
    build: AuditBuild, database_path: str | Path
) -> list[dict[str, Any]]:
    """Attach database-history evidence to every non-reproducing source node."""
    database_path = Path(database_path).resolve()
    family_root = database_path / "input/kinetics/families"
    by_event_id = {record["event_id"]: record for record in build.audit["records"]}
    stale_nodes = []
    for source, reproduction in sorted(
        build.source_reproductions.items(), key=lambda item: item[0]
    ):
        if reproduction["rate_matches"]:
            continue
        family_label, _, node_label = source
        family = build.compiler.kinetics_database.families[family_label]
        stored_entry = family.rules.entries[node_label][0]
        stored_count = getattr(
            getattr(stored_entry.data, "uncertainty", None), "N", None
        )
        representative = by_event_id[reproduction["representative_event_id"]]
        training_contributors = [
            contributor
            for contributor in representative["contributors"]
            if contributor["source_kind"] == "training reaction"
        ]
        family_path = family_root / family_label
        rules_path = family_path / "rules.py"
        training_path = family_path / "training/reactions.py"
        rule_commit = _git_blame_entry_kinetics_commit(
            database_path,
            rules_path,
            node_label,
        )
        contributor_history = []
        for contributor in training_contributors:
            commit = _git_entry_addition_commit(
                database_path, training_path, contributor["label"]
            )
            contributor_history.append(
                {
                    "index": contributor["index"],
                    "label": contributor["label"],
                    "entry_commit": commit,
                    "entry_present_in_training_file_at_rule_commit": (
                        _entry_present_at_commit(
                            database_path,
                            rule_commit,
                            training_path,
                            contributor["label"],
                        )
                    ),
                }
            )

        training_map = _autogenerated_training_map(
            family,
            build.compiler.thermo_database,
            build.compiler._contributor_cache,
        )
        refit = _fit_autogenerated_node(
            family,
            node_label,
            [reaction for _, reaction in training_map[node_label]],
        )
        current_count = len(training_contributors)
        later = [
            item
            for item in contributor_history
            if not item["entry_present_in_training_file_at_rule_commit"]
        ]
        if (
            stored_count == current_count == 1
            and type(stored_entry.data).__name__.endswith("BM")
            and type(refit).__name__ == "Arrhenius"
        ):
            contributor = contributor_history[0]
            diagnosis = (
                "Legacy single-reaction BM rule: the stored node at database "
                f"commit {rule_commit[:10]} is BM, while current RMG-Py "
                "d012688769 changes N=1 generation to averaged Arrhenius; "
                f"contributor {contributor['index']} "
                f"({contributor['label']}) is present in the historical "
                f"training file and was added at "
                f"{contributor['entry_commit'][:10]}."
            )
        elif stored_count == current_count and not later:
            diagnosis = (
                f"Legacy {current_count}-reaction fit: current matching has the "
                "same N and every named entry exists in the historical training "
                f"file at stored-kinetics commit {rule_commit[:10]}, but the "
                "current RMG fitter/thermo path does not reproduce the "
                "unregenerated fit."
            )
        else:
            grouped = defaultdict(list)
            for contributor in later:
                grouped[contributor["entry_commit"]].append(contributor)
            additions = "; ".join(
                ", ".join(f"{item['index']} ({item['label']})" for item in items)
                + f" at {commit[:10]}"
                for commit, items in sorted(grouped.items())
            )
            diagnosis = (
                f"Contributor-set drift: stored rule commit {rule_commit[:10]} "
                f"records N={stored_count}, current matching finds N={current_count}; "
                f"entries absent from that rule commit are {additions}, and the "
                "full autogenerated tree was not regenerated."
            )
        reproduction["diagnosis"] = diagnosis
        reproduction["diagnosis_evidence"] = {
            "stored_rule_commit": rule_commit,
            "stored_training_reaction_count": stored_count,
            "current_training_reaction_count": current_count,
            "stored_kinetics_type": type(stored_entry.data).__name__,
            "refit_kinetics_type": type(refit).__name__,
            "contributors": contributor_history,
        }
        stale_nodes.append(
            {
                "family": family_label,
                "node": node_label,
                "original_origin": reproduction["origin"],
                "maximum_relative_error": reproduction["relative_error"],
                "dependent_event_ids": reproduction["dependent_event_ids"],
                "flagged_contributor_present": any(
                    contributor["flagged"]
                    for contributor in representative["contributors"]
                ),
                "diagnosis": diagnosis,
                "diagnosis_evidence": reproduction["diagnosis_evidence"],
            }
        )
    return stale_nodes


def _verify_one(
    build: AuditBuild, audit_record, trace_override=None, *, require_complete=True
):
    event_id = audit_record["event_id"]
    reaction, runtime_trace = build.contexts[event_id]
    if reaction is None:
        raise ValueError("record has no regenerated reaction")
    listed = trace_override or audit_record
    if require_complete and _contributor_keys(listed) != _contributor_keys(
        runtime_trace
    ):
        raise ValueError("listed contributor set is incomplete or contains extras")
    record = next(
        item for item in build.artifact["records"] if item["event_id"] == event_id
    )
    recomputed = _rate_table_from_listed_contributors(build, reaction, listed)
    if recomputed is None or record["k_table"] is None:
        raise ValueError("record has no recomputable rate table")
    relative_errors = [
        abs(actual - expected) / abs(expected)
        for actual, expected in zip(recomputed["k"], record["k_table"]["k"])
    ]
    rate_matches = recomputed["T"] == record["k_table"]["T"] and all(
        error <= RATE_REPRODUCTION_RTOL for error in relative_errors
    )
    if not rate_matches:
        raise ValueError(
            "RMG estimator does not reproduce the compiled rate for "
            f"{event_id} ({audit_record['origin']}, {audit_record['node']}): "
            f"maximum relative error {max(relative_errors):.12g}"
        )
    return {
        "event_id": event_id,
        "origin": audit_record["origin"],
        "node": audit_record["node"],
        "rate_matches": True,
        "max_relative_error": max(relative_errors),
    }


def verify_build(build: AuditBuild) -> dict[str, Any]:
    artifact_ids = [record["event_id"] for record in build.artifact["records"]]
    audit_ids = [record["event_id"] for record in build.audit["records"]]
    if len(audit_ids) != len(set(audit_ids)) or sorted(audit_ids) != sorted(
        artifact_ids
    ):
        raise ValueError("audit is not a one-to-one cover of the event set")
    if build.audit["event_set_sha256"] != build.event_set_path.stem:
        raise ValueError("audit event-set hash does not match its artifact")
    verify_stale_source_classification(
        build.audit["records"],
        build.source_reproductions,
        build.historical_reproductions,
    )

    source_reproductions = build.source_reproductions
    if len(source_reproductions) < 3:
        raise ValueError("fewer than three distinct rate sources were found")
    checked = [
        {
            "family": reproduction["family"],
            "origin": reproduction["origin"],
            "node": reproduction["node"],
            "representative_event_id": reproduction["representative_event_id"],
            "dependent_record_count": len(reproduction["dependent_event_ids"]),
            "rate_matches": reproduction["rate_matches"]
            or build.historical_reproductions.get(source, {}).get(
                "rate_matches", False
            ),
            "current_rate_matches": reproduction["rate_matches"],
            "max_relative_error": reproduction["relative_error"],
            "historical_resolution": build.historical_reproductions.get(
                source, {}
            ).get("resolution"),
            "historical_max_relative_error": build.historical_reproductions.get(
                source, {}
            ).get("maximum_relative_error"),
            "error": reproduction["error"],
        }
        for source, reproduction in sorted(
            source_reproductions.items(), key=lambda item: item[0]
        )
    ]

    by_source = {}
    for record in build.audit["records"]:
        if (
            record["resolution"] == "RESOLVED"
            and record["contributors"]
            and build.artifact["records"][artifact_ids.index(record["event_id"])][
                "k_table"
            ]
        ):
            by_source.setdefault(
                (record["family"], record["origin"], record["node"]), record
            )

    removed_rejected = False
    for candidate in by_source.values():
        training_indexes = [
            index
            for index, item in enumerate(candidate["contributors"])
            if item["source_kind"] == "training reaction"
        ]
        if candidate["origin"] != "autogenerated node" or len(training_indexes) < 2:
            continue
        try:
            _verify_one(build, candidate)
        except ValueError:
            continue
        for index in training_indexes:
            corrupted = deepcopy(candidate)
            del corrupted["contributors"][index]
            try:
                _verify_one(
                    build,
                    candidate,
                    trace_override=corrupted,
                    require_complete=False,
                )
            except ValueError:
                removed_rejected = True
                break
        if removed_rejected:
            break
    if not removed_rejected:
        raise AssertionError("removing a contributor did not break verification")
    reproduced_count = sum(item["rate_matches"] for item in checked)
    current_reproduced_count = sum(
        item["current_rate_matches"] for item in checked
    )
    historical_reproduced_count = sum(
        item["historical_resolution"] is not None and item["rate_matches"]
        for item in checked
    )
    available_origins = sorted({item["origin"] for item in checked})
    return {
        "available_origins": available_origins,
        "checked_all_available_origins": True,
        "checked_all_source_nodes": True,
        "source_node_count": len(checked),
        "reproduced_source_node_count": reproduced_count,
        "current_reproduced_source_node_count": current_reproduced_count,
        "historical_reproduced_source_node_count": historical_reproduced_count,
        "stale_source_node_count": len(checked) - reproduced_count,
        "trace_correctness": checked,
        "removed_contributor_rejected": removed_rejected,
    }


def render_report(build: AuditBuild, reproduction_command: str) -> str:
    counts = Counter(record["origin"] for record in build.audit["records"])
    unresolved = [
        record
        for record in build.audit["records"]
        if record["resolution"].startswith("UNRESOLVED")
    ]
    lines = [
        "# C8 rate-source provenance audit of the compiled PS event set",
        "",
        f"Audit hash: `{build.audit_path.stem}`",
        "",
        f"Event-set artifact hash: `{build.event_set_path.stem}`",
        "",
        "Reproduction command:",
        "",
        f"```bash\n{reproduction_command}\n```",
        "",
    ]
    oracle = build.audit.get("refit_oracle")
    if oracle is not None:
        control = oracle["positive_control"]
        lines.extend(
            [
                "## Refit oracle",
                "",
                "The audit calls `rmgpy.data.kinetics.family._make_rule`, the "
                "same function called by "
                "`KineticsFamily.make_bm_rules_from_template_rxn_map` during "
                "`KineticsFamily.make_tree`.",
                "",
                "RMG selects the node training set with "
                "`get_reaction_matches(remove_degeneracy=True, "
                "get_reverse=True)`. `_make_rule` uses "
                "`ArrheniusBM.fit_to_reactions` for multi-reaction nodes and "
                "RMG's averaging fallback for N=1 or negative E0, with "
                f"`Tref={oracle['Tref_K']:g} K`, `fmax={oracle['fmax']:g}`, "
                "the training-entry ranks, and thermo assigned by "
                "`get_training_set` from the loaded ThermoDatabase for dHrxn.",
                "",
                "Rates are evaluated in RMG SI units at 300–1000 K in 25 K "
                "increments, using each event's reaction-order unit. The refit "
                "is round-tripped through RMG's `rules.py` representation "
                "before comparison.",
                "",
                "Positive control: a scratch copy of "
                f"`{control['family']}` was cleaned, regenerated by "
                "`make_tree`, saved, reloaded, and refitted. "
                f"All {control['source_node_count']} source nodes reproduced; "
                "maximum relative error "
                f"`{control['maximum_relative_error']:.12g}` against "
                f"`RATE_REPRODUCTION_RTOL={RATE_REPRODUCTION_RTOL:g}`.",
                "",
            ]
        )
    legacy = build.audit.get("legacy_rate_oracle")
    if legacy is not None:
        lines.extend(
            [
                "## Legacy-path oracle",
                "",
                "RMG-Py commit "
                f"`{legacy['single_reaction_switch_commit']}` switched N=1 "
                "autogenerated rules away from the prior "
                "`ArrheniusBM.fit_to_reactions` path. This oracle reproduces "
                "that pre-switch code, including dHrxn(T), the 300–1500 K "
                "fit grid, rule ranks and units.",
                "",
                "Historical database inputs were extracted into scratch only "
                "with `git show <commit>:<path>`. The database repository was "
                "not checked out or modified. Thermo was loaded in the exact "
                "`generateTree.py` library order: "
                + ", ".join(f"`{name}`" for name in legacy["thermo_libraries"])
                + ".",
                "",
                "The perturbed-A control multiplied contributor "
                f"{legacy['perturbation_control']['contributor']['index']} by "
                f"{legacy['perturbation_control']['factor']:g}; its maximum "
                "relative error was "
                f"`{legacy['perturbation_control']['maximum_relative_error']:.12g}` "
                "and it correctly failed reproduction.",
                "",
                "## Historically reproduced autogenerated nodes",
                "",
            ]
        )
        for historical in build.audit.get("historical_nodes", []):
            contributors = ", ".join(
                f"{item['index']} ({item['label']})"
                for item in historical["contributors"]
            )
            thermo_probe = historical.get(
                "historical_training_live_thermo_relative_error"
            )
            lines.extend(
                [
                    f"### {historical['family']} — {historical['node']}",
                    "",
                    f"Resolution: `{historical['resolution']}`",
                    "",
                    "Historical maximum relative error: "
                    f"`{historical['maximum_relative_error']:.12g}`; current-path "
                    "maximum relative error: "
                    f"`{historical['current_maximum_relative_error']:.12g}`.",
                    "",
                    "Historical stored rule versus live stored rule maximum "
                    "relative error: "
                    f"`{historical['historical_live_stored_relative_error']:.12g}`.",
                    "",
                    "Diagnosis: " + historical["change_that_reproduces"] + ".",
                    "",
                    *(
                        [
                            "Historical training with live thermo still has "
                            f"relative error `{thermo_probe:.12g}`; historical "
                            "thermo moves it into tolerance.",
                            "",
                        ]
                        if thermo_probe is not None
                        else []
                    ),
                    f"Contributors: {contributors}.",
                    "",
                    "Contributors 5002 or 5003 in stored fit: "
                    + ("yes" if historical["contains_5002_or_5003"] else "no"),
                    "",
                    "Flagged contributor present: "
                    + ("yes" if historical["flagged_contributor_present"] else "no"),
                    "",
                    "Dependent records:",
                    "",
                    *[
                        f"- `{event_id}`"
                        for event_id in historical["dependent_event_ids"]
                    ],
                    "",
                ]
            )
    lines.extend(
        [
            "## Counts by origin",
            "",
            "| Origin | Records |",
            "|---|---:|",
        ]
    )
    origins = (
        "exact training match",
        "library",
        "rate rule node",
        "averaged node",
        "autogenerated node",
        "historical autogenerated node",
        "UNRESOLVED",
    )
    for origin in origins:
        count = len(unresolved) if origin == "UNRESOLVED" else counts.get(origin, 0)
        lines.append(f"| {origin} | {count} |")

    lines.extend(["", "## Stale autogenerated nodes", ""])
    stale_nodes = build.audit.get("stale_nodes")
    if stale_nodes is None:
        stale_by_source = defaultdict(list)
        for record in unresolved:
            if record["resolution"] == "UNRESOLVED:stale-node":
                stale_by_source[(record["family"], record["node"])].append(record)
        stale_nodes = []
        for (family, node), records in sorted(stale_by_source.items()):
            relative_errors = [
                record["relative_error"]
                for record in records
                if record["relative_error"] is not None
            ]
            stale_nodes.append(
                {
                    "family": family,
                    "node": node,
                    "maximum_relative_error": (
                        max(relative_errors) if relative_errors else None
                    ),
                    "flagged_contributor_present": any(
                        contributor["flagged"]
                        for record in records
                        for contributor in record["contributors"]
                    ),
                    "dependent_event_ids": [record["event_id"] for record in records],
                    "diagnosis": records[0].get("stale_node_diagnosis", "Unavailable."),
                }
            )
    if not stale_nodes:
        lines.append("None.")
    for stale in stale_nodes:
        error = stale["maximum_relative_error"]
        lines.extend(
            [
                f"### {stale['family']} — {stale['node']}",
                "",
                "Maximum relative error: "
                + (f"`{error:.12g}`" if error is not None else "unavailable"),
                "",
                "Diagnosis: " + stale["diagnosis"],
                "",
                "Flagged contributor present: "
                + ("yes" if stale["flagged_contributor_present"] else "no"),
                "",
                "Dependent records:",
                "",
                *[f"- `{event_id}`" for event_id in stale["dependent_event_ids"]],
                "",
            ]
        )

    dependencies = defaultdict(set)
    flagged_entries = {}
    for record in build.audit["records"]:
        for contributor in record["contributors"]:
            if contributor["flagged"]:
                key = _entry_key(contributor)
                dependencies[key].add(record["event_id"])
                flagged_entries[key] = contributor
    lines.extend(["", "## Flagged entries", ""])
    if not flagged_entries:
        lines.append("None.")
    for key in sorted(flagged_entries, key=lambda item: tuple(str(x) for x in item)):
        contributor = flagged_entries[key]
        lines.extend(
            [
                f"### {contributor['family']} — {contributor['source_kind']} {contributor['index']}: {contributor['label']}",
                "",
                f"Flag terms: {', '.join(contributor['flag_terms'])}",
                "",
                "Dependent records:",
                "",
                *[f"- `{event_id}`" for event_id in sorted(dependencies[key])],
                "",
                "Full database fields:",
                "",
                "```json",
                json.dumps(contributor, indent=2, sort_keys=True, ensure_ascii=True),
                "```",
                "",
            ]
        )

    lines.extend(["", "## UNRESOLVED records", ""])
    if not unresolved:
        lines.append("None.")
    else:
        lines.extend(
            f"- `{record['event_id']}` — {record['family']} [{';'.join(record['template_labels'])}]: {record['reason']}"
            for record in unresolved
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("database")
    parser.add_argument("output")
    parser.add_argument("--report")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    build = build_audit(args.database, args.output)
    verification = verify_build(build) if args.verify else None
    if args.report:
        output = Path(args.output).resolve()
        command = (
            "nohup env PYTHONHASHSEED=0 PYTHONPATH=$PWD "
            f"{shlex.quote(sys.executable)} -m rmgpy.kmc.provenance "
            f"{shlex.quote(str(Path(args.database).resolve()))} "
            f"{shlex.quote(str(output))} --verify --report "
            f"{shlex.quote(str(Path(args.report).resolve()))} "
            "> /tmp/i019-provenance.log 2>&1 & pid=$!; wait $pid"
        )
        Path(args.report).write_text(render_report(build, command))
    print(
        json.dumps(
            {
                "audit_path": str(build.audit_path),
                "event_set_path": str(build.event_set_path),
                "verification": verification,
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
