import hashlib
import json
from types import SimpleNamespace

import pytest

from rmgpy.data.base import Entry
from rmgpy.data.reference import Article, Reference
from rmgpy.kmc.provenance import (
    FLAG_TERMS,
    entry_flag_terms,
    qualify_stale_source_records,
    render_report,
    serialize_entry,
    verify_stale_source_classification,
    write_content_addressed_audit,
)


def test_fixed_flag_terms_cover_reference_and_clean_controls():
    assert FLAG_TERMS == (
        "Kruse",
        "Broadbelt",
        "Levine",
        "polystyrene",
        "polyethylene",
        "polypropylene",
        "polymer",
        "pyrolysis",
        "TGA",
        "thermogravimetr",
        "oligomer",
        "plastic",
        "Poutsma",
    )

    flagged = Entry(
        index=1,
        label="flagged",
        reference=Reference(authors=["T. M. Kruse"], title="A rate"),
    )
    clean = Entry(
        index=2,
        label="clean",
        short_desc="Gas-phase radical kinetics",
        reference=Reference(authors=["A. N. Other"], title="A clean rate"),
    )

    assert entry_flag_terms(flagged) == ["Kruse"]
    assert entry_flag_terms(clean) == []


def test_entry_serialization_keeps_full_bibliographic_record():
    entry = Entry(
        index=7,
        label="node;child",
        rank=3,
        short_desc="Measured rate",
        long_desc="Long provenance",
        reference_type="experimental",
        reference=Article(
            authors=["A. Author", "B. Writer"],
            title="Rate source",
            journal="J. Kinetics",
            volume="12",
            number="3",
            pages="4-8",
            year="2001",
            doi="10.1000/example",
            url="https://example.test/rate",
        ),
    )

    assert serialize_entry(entry, "rate rule", "H_Abstraction", weight=0.5) == {
        "family": "H_Abstraction",
        "source_kind": "rate rule",
        "index": 7,
        "label": "node;child",
        "rank": 3,
        "weight": 0.5,
        "short_desc": "Measured rate",
        "long_desc": "Long provenance",
        "reference_type": "experimental",
        "reference": {
            "type": "Article",
            "authors": ["A. Author", "B. Writer"],
            "title": "Rate source",
            "journal": "J. Kinetics",
            "volume": "12",
            "number": "3",
            "pages": "4-8",
            "year": "2001",
            "doi": "10.1000/example",
            "url": "https://example.test/rate",
        },
        "flag_terms": [],
        "flagged": False,
    }


def test_audit_file_stem_is_sha256_of_canonical_bytes(tmp_path):
    audit = {"z": [2, 1], "a": "value"}
    path = write_content_addressed_audit(audit, tmp_path)
    payload = path.read_bytes()

    assert payload == b'{"a":"value","z":[2,1]}'
    assert path.stem == hashlib.sha256(payload).hexdigest()
    assert json.loads(payload) == audit


def test_stale_source_qualifies_every_dependent_record():
    contributor = {
        "family": "Example",
        "source_kind": "training reaction",
        "index": 7,
        "label": "training",
        "flagged": True,
    }
    records = [
        {
            "event_id": "evt_1",
            "family": "Example",
            "resolution": "RESOLVED",
            "origin": "autogenerated node",
            "node": "Root_child",
            "contributors": [contributor],
        },
        {
            "event_id": "evt_2",
            "family": "Example",
            "resolution": "RESOLVED",
            "origin": "autogenerated node",
            "node": "Root_child",
            "contributors": [contributor],
        },
        {
            "event_id": "evt_other",
            "family": "Example",
            "resolution": "RESOLVED",
            "origin": "rate rule node",
            "node": "Other",
            "contributors": [],
        },
    ]
    source_reproductions = {
        ("Example", "autogenerated node", "Root_child"): {
            "rate_matches": False,
            "dependent_event_ids": ["evt_1", "evt_2"],
            "records": {
                "evt_1": {
                    "stored_rate": {"T": [1000.0], "k": [10.0]},
                    "refit_rate": {"T": [1000.0], "k": [5.0]},
                    "relative_error": 0.5,
                },
                "evt_2": {
                    "stored_rate": {"T": [1000.0], "k": [20.0]},
                    "refit_rate": {"T": [1000.0], "k": [10.0]},
                    "relative_error": 0.5,
                },
            },
        }
    }

    qualify_stale_source_records(records, source_reproductions)

    for record in records[:2]:
        assert record["resolution"] == "UNRESOLVED:stale-node"
        assert record["origin"] == "UNRESOLVED:stale-node"
        assert record["original_origin"] == "autogenerated node"
        assert record["stored_rate"]["k"][0] == pytest.approx(
            2.0 * record["refit_rate"]["k"][0]
        )
        assert record["relative_error"] == pytest.approx(0.5)
        assert record["contributors"] == [contributor]
    assert records[2]["resolution"] == "RESOLVED"


def test_stale_verifier_rejects_unqualified_nonreproducing_node(monkeypatch):
    record = {
        "event_id": "evt_stale",
        "family": "Example",
        "resolution": "RESOLVED",
        "origin": "autogenerated node",
        "node": "Root_child",
        "contributors": [{"family": "Example", "index": 7, "label": "training"}],
    }
    source_reproductions = {
        ("Example", "autogenerated node", "Root_child"): {
            "rate_matches": False,
            "dependent_event_ids": ["evt_stale"],
            "records": {
                "evt_stale": {
                    "stored_rate": {"T": [1000.0], "k": [10.0]},
                    "refit_rate": {"T": [1000.0], "k": [5.0]},
                    "relative_error": 0.5,
                }
            },
        }
    }
    qualify_stale_source_records([record], source_reproductions)
    monkeypatch.setitem(record, "resolution", "RESOLVED")

    with pytest.raises(ValueError, match="not labelled UNRESOLVED:stale-node"):
        verify_stale_source_classification([record], source_reproductions)


def test_report_lists_stale_node_and_counts_it_unresolved(tmp_path):
    contributor = {
        "family": "Example",
        "source_kind": "training reaction",
        "index": 7,
        "label": "flagged training",
        "flag_terms": ["polymer"],
        "flagged": True,
    }
    build = SimpleNamespace(
        audit={
            "records": [
                {
                    "event_id": "evt_stale",
                    "family": "Example",
                    "template_labels": ["Root_child"],
                    "resolution": "UNRESOLVED:stale-node",
                    "origin": "UNRESOLVED:stale-node",
                    "original_origin": "autogenerated node",
                    "reason": "stale",
                    "node": "Root_child",
                    "relative_error": 0.5,
                    "contributors": [contributor],
                }
            ]
        },
        audit_path=tmp_path / "audit-sha.json",
        event_set_path=tmp_path / "event-sha.json",
    )

    report = render_report(build, "reproduce-command")

    assert "| autogenerated node | 0 |" in report
    assert "| UNRESOLVED | 1 |" in report
    assert "## Stale autogenerated nodes" in report
    assert "### Example — Root_child" in report
    assert "Maximum relative error: `0.5`" in report
    assert "- `evt_stale`" in report
    assert "Flagged contributor present: yes" in report
