import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest

from rmgpy.kmc.compiler import validate_artifact
from rmgpy.kmc.provenance import (
    RATE_REPRODUCTION_RTOL,
    run_autogenerated_oracle_positive_control,
    run_legacy_rate_oracle,
)


pytestmark = [
    pytest.mark.slow,
    pytest.mark.skipif(
        os.environ.get("RMG_KMC_SLOW") != "1",
        reason="set RMG_KMC_SLOW=1 to run the real database provenance audit",
    ),
]

REPO_ROOT = Path(__file__).resolve().parents[3]
DB_PATH = os.environ.get("RMG_DATABASE_PATH", str(REPO_ROOT.parent / "RMG-database"))


def test_autogenerated_refit_oracle_reproduces_fresh_tree():
    result = run_autogenerated_oracle_positive_control(DB_PATH)

    assert result["family"] == "Bimolec_Hydroperoxide_Decomposition"
    assert result["source_node_count"] >= 3
    assert result["maximum_relative_error"] <= RATE_REPRODUCTION_RTOL
    assert result["rate_matches"] is True


def test_legacy_rate_oracle_reproduces_historical_nodes_and_rejects_perturbation():
    result = run_legacy_rate_oracle(DB_PATH)

    assert result["source_node_count"] == 6
    assert all(node["rate_matches"] for node in result["nodes"])
    assert max(node["maximum_relative_error"] for node in result["nodes"]) <= (
        RATE_REPRODUCTION_RTOL
    )
    drift = next(node for node in result["nodes"] if node["training_reaction_count"] == 5)
    assert [(item["index"], item["label"]) for item in drift["contributors"]] == [
        (33, "C3H3 + C7H7 <=> C10H10"),
        (47, "C3H3 + C3H3 <=> C6H6-3"),
        (125, "C3H5 + C3H5 <=> C6H10-2"),
        (126, "C3H5 + C2H5 <=> C5H10-2"),
        (127, "C3H5 + CH3 <=> C4H8-2"),
    ]
    assert drift["contains_5002_or_5003"] is False
    assert result["perturbation_control"]["factor"] == 2.0
    assert result["perturbation_control"]["rate_matches"] is False
    assert result["perturbation_control"]["maximum_relative_error"] > (
        RATE_REPRODUCTION_RTOL
    )


@pytest.fixture(scope="module")
def seeded_audits(tmp_path_factory):
    processes = []
    for seed in ("0", "4242"):
        output = tmp_path_factory.mktemp(f"provenance-{seed}")
        stdout_path = output / "stdout.log"
        stderr_path = output / "stderr.log"
        stdout = stdout_path.open("w")
        stderr = stderr_path.open("w")
        environment = os.environ.copy()
        environment.update(
            {
                "PYTHONHASHSEED": seed,
                "PYTHONPATH": str(REPO_ROOT),
                "MPLCONFIGDIR": str(output / "matplotlib"),
            }
        )
        process = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "rmgpy.kmc.provenance",
                DB_PATH,
                str(output),
                "--verify",
            ],
            cwd=REPO_ROOT,
            env=environment,
            stdout=stdout,
            stderr=stderr,
        )
        processes.append((seed, output, process, stdout, stderr))
    for seed, output, process, stdout, stderr in processes:
        process.wait(timeout=20 * 60)
        stdout.close()
        stderr.close()
        assert (
            process.returncode == 0
        ), f"PYTHONHASHSEED={seed} failed; see {output / 'stderr.log'}"
    results = []
    for seed, output, _, _, _ in processes:
        summary = json.loads((output / "stdout.log").read_text().splitlines()[-1])
        results.append((seed, output, summary))
    return results


def test_every_validated_artifact_record_appears_once(seeded_audits):
    _, _, summary = seeded_audits[0]
    artifact_path = Path(summary["event_set_path"])
    audit_path = Path(summary["audit_path"])
    artifact = json.loads(artifact_path.read_bytes())
    audit = json.loads(audit_path.read_bytes())
    validate_artifact(artifact)

    event_ids = [record["event_id"] for record in artifact["records"]]
    audited_ids = [record["event_id"] for record in audit["records"]]
    assert len(audited_ids) == len(set(audited_ids))
    assert sorted(audited_ids) == sorted(event_ids)
    assert audit["event_set_sha256"] == artifact_path.stem
    assert artifact_path.stem == hashlib.sha256(artifact_path.read_bytes()).hexdigest()


def test_every_source_node_is_reproduced_or_labelled_stale(seeded_audits):
    _, _, summary = seeded_audits[0]
    verification = summary["verification"]
    checked = verification["trace_correctness"]
    audit = json.loads(Path(summary["audit_path"]).read_bytes())

    assert verification["checked_all_source_nodes"] is True
    assert len(checked) == verification["source_node_count"]
    assert verification["reproduced_source_node_count"] + verification[
        "stale_source_node_count"
    ] == len(checked)
    assert len(
        {(item["family"], item["origin"], item["node"]) for item in checked}
    ) == len(checked)

    stale_results = {
        (item["family"], item["origin"], item["node"]): item
        for item in checked
        if not item["rate_matches"]
    }
    stale_records = [
        record
        for record in audit["records"]
        if record["resolution"] == "UNRESOLVED:stale-node"
    ]
    assert not stale_results
    assert {
        (record["family"], record["original_origin"], record["node"])
        for record in stale_records
    } == set(stale_results)
    assert all(record["origin"] == "UNRESOLVED:stale-node" for record in stale_records)
    assert all("stored_rate" in record for record in stale_records)
    assert all("refit_rate" in record for record in stale_records)
    assert all("relative_error" in record for record in stale_records)
    assert all("stale_node_diagnosis" in record for record in stale_records)
    stale_nodes = audit["stale_nodes"]
    assert {
        (item["family"], item["original_origin"], item["node"]) for item in stale_nodes
    } == set(stale_results)
    assert not stale_nodes
    historical_nodes = audit["historical_nodes"]
    assert len(historical_nodes) == 6
    assert all(item["rate_matches"] for item in historical_nodes)
    assert all(
        item["resolution"].startswith("RESOLVED:historical-")
        for item in historical_nodes
    )
    assert all(item["live_stored_rate_matches"] for item in historical_nodes)
    assert all(
        item["historical_live_stored_relative_error"] <= RATE_REPRODUCTION_RTOL
        for item in historical_nodes
    )
    assert all(
        item["flagged_contributor_present"]
        == any(contributor["flagged"] for contributor in item["contributors"])
        for item in historical_nodes
    )
    expanded = next(
        item
        for item in historical_nodes
        if item["training_reaction_count"] == 5
    )
    assert [contributor["index"] for contributor in expanded["contributors"]] == [
        33,
        47,
        125,
        126,
        127,
    ]
    assert expanded["contains_5002_or_5003"] is False
    assert verification["historical_reproduced_source_node_count"] == 6
    assert verification["stale_source_node_count"] == 0
    assert verification["removed_contributor_rejected"] is True

    oracle = audit["refit_oracle"]
    assert oracle["same_fit_function_as_tree_generation"] is True
    assert oracle["refit_function"] == "rmgpy.data.kinetics.family._make_rule"
    assert oracle["positive_control"]["rate_matches"] is True
    assert oracle["positive_control"]["maximum_relative_error"] <= (
        RATE_REPRODUCTION_RTOL
    )


def test_audit_hash_is_cross_interpreter_deterministic(seeded_audits):
    first = Path(seeded_audits[0][2]["audit_path"])
    second = Path(seeded_audits[1][2]["audit_path"])
    assert first.stem == second.stem
    assert first.read_bytes() == second.read_bytes()
