#!/usr/bin/env python
# encoding: utf-8

name = "Electron_Reverse_Recombination/groups"
shortDesc = ""
longDesc = """
The same cut-down cation recombination family as electron_propagation_data -- a lithium cation and
a radical recombining into a neutral molecule, with the charge closed by an electron that is never
listed as a reactant. It is duplicated here so that the reverse-flip test can own a training
depository whose single entry is written backward, without disturbing the forward fixture.
"""

template(reactants=["Root"], products=["Y_Y"], ownReverse=False)

reverse = "Cation_Bond_Dissociation"
reversible = True

autoGenerated = True
reactantNum = 2
productNum = 1

allowChargedSpecies = True
electrons = -1

recipe(
    actions=[
        ["LOSE_CHARGE", "*1", 1],
        ["FORM_BOND", "*1", 1, "*2"],
        ["LOSE_RADICAL", "*2", 1],
    ]
)

entry(
    index=0,
    label="Root",
    group="""
1 *1 Li+ u0 p0 c+1
2 *2 R   u1
""",
    kinetics=None,
)

tree(
    """
L1: Root
"""
)
