"""Generate the i099 demonstration decks: two parameterisations x two temperatures.

ARM 'scalar'   -- today's parameterisation: k_scission / k_unzip are bare rate
                  constants (the literal poly_106 values, 1.0 and 100.0 s^-1).
                  k(T) = A, so nothing in the condensed phase sees T.
ARM 'arrhenius' -- the SAME backbone-break event declared through k_homolysis,
                  which the solver evaluates as A*T^n*exp(-Ea/(R*T)) at its
                  runtime temperature (rmgpy/solver/polymer.pyx:7356-7360).
                  Parameters recovered from the derivation already in
                  /home/alon/runs/RMG/poly_101/input.py:73-78.

The gas outlet is deliberately temperature-INDEPENDENT in BOTH arms, so every
bit of temperature response in the 'arrhenius' arm comes from the derived
scission parameters and nothing else:
  scalar arm    -> k_unzip        = 1.0 s^-1   (bare constant, by construction)
  arrhenius arm -> k_depropagation = {A: 1.0, n: 0, Ea: 0}  -> k(T) = 1.0 s^-1
Ea = 0 there is not a claim that the depropagation barrier is zero: it is the
honest record that this project has NO basis for that barrier (see the report).

Gas-phase chemistry is switched off (kineticsFamilies='none', no libraries) so
the only dynamics in the reactor are the polymer moment kernels.  That is what
makes the two-temperature comparison attributable.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# --- the derived backbone-scission triplet -----------------------------------
# poly_101/input.py:73-78, verbatim:
#   "Chain-initiation kinetics at 1100 K from Arrhenius estimate for the
#    benzylic-CH2-CH2 linkage (BDE ~65 kcal/mol, A ~ 1e16 s^-1):
#    k = 1e16 * exp(-65000/(R*1100)) ~ 1.3e3 s^-1 (per link)."
# The pair being collapsed there is exactly (A, Ea); recover it:
A_SCISSION = 1.0e16          # s^-1, per backbone link
N_SCISSION = 0.0             # two-parameter Arrhenius: the derivation fixes A
                             # against Ea at one temperature and has no third
                             # degree of freedom.  n != 0 would re-scale A.
EA_SCISSION = 65.0 * 4184.0  # 65 kcal/mol -> 271960.0 J/mol

# --- the admitted placeholder ------------------------------------------------
A_OUTLET = 1.0               # s^-1 per chain end.  NO basis; a fixed valve.

TEMPERATURES = (700.0, 900.0)

HEADER = """# i099 demonstration deck -- ARM '{arm}', T = {T:g} K.
# Generated by make_decks.py; do not hand-edit.
#
# Polystyrene: the backbone bond is a benzylic C-C of the same class the
# poly_101 derivation is written for (BDE ~65 kcal/mol, A ~ 1e16 s^-1), and PS
# is the archetypal depropagating polymer, so the monomer outlet is real
# chemistry rather than a fiction bolted on to make the demo move.

database(
    thermoLibraries=['primaryThermoLibrary', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC',
                     'DFT_QCI_thermo', 'CBS_QB3_1dHR'],
    reactionLibraries=[],
    transportLibraries=['PrimaryTransportLibrary'],
    seedMechanisms=[],
    kineticsDepositories='default',
    kineticsFamilies='none',
    kineticsEstimator='rate rules',
)

species(
    label='N2',
    reactive=False,
    structure=SMILES("N#N"),
)

species(
    label='styrene',
    reactive=True,
    structure=SMILES("C=Cc1ccccc1"),
)

"""

POOL_SCALAR = """polymer(
    label='PS',
    monomer='[CH2][CH]c1ccccc1',
    end_groups=['[CH3]', '[H]'],
    cutoff=3,
    Mn=5000.0,
    Mw=6000.0,
    initial_mass=1.0,
    monomer_product='C=Cc1ccccc1',
    # TODAY. Bare rate constants: k(T) = A, no onset, no window.
    k_scission=1.0,
    k_unzip={A_OUTLET:g},
)
"""

POOL_ARRHENIUS = """polymer(
    label='PS',
    monomer='[CH2][CH]c1ccccc1',
    end_groups=['[CH3]', '[H]'],
    cutoff=3,
    Mn=5000.0,
    Mw=6000.0,
    initial_mass=1.0,
    monomer_product='C=Cc1ccccc1',
    k_scission=0.0,
    k_unzip=0.0,
    # DERIVED. Same random backbone-break event as k_scission (rmgpy/rmg/
    # input.py:481-491), declared as the Arrhenius triplet the solver
    # evaluates at its runtime T.
    #   k(T) = A * T^n * exp(-Ea/(R*T));  k(1100 K) = 1.219e3 s^-1
    # NOTE: a brace literal, not dict(...).  Deck files are exec'd with
    # __builtins__ = None (rmgpy/rmg/input.py:2442), so dict() raises
    # "TypeError: 'NoneType' object is not subscriptable" -- which is how the
    # docstring examples at input.py:305-309 and :359-361 are written.
    k_homolysis={{'A': {A_SCISSION:g}, 'n': {N_SCISSION:g}, 'Ea': {EA_SCISSION:.1f}}},
    # PLACEHOLDER, no basis on record.  Ea = 0 records the absence of a known
    # barrier, and keeps the outlet temperature-independent so the measured
    # T-response is attributable to k_homolysis alone.
    k_depropagation={{'A': {A_OUTLET:g}, 'n': 0.0, 'Ea': 0.0}},
)
"""

TAIL = """
pp = polymer_phase(
    label='PS_melt',
    species=['PS', 'N2'],
    solvent='N2',
    density=(1050.0, 'kg/m^3'),
)

hybridPolymerReactor(
    temperature=({T:g}, 'K'),
    pressure=(1.0, 'bar'),
    initialMoles={{
        'N2': 0.99,
        'PS': 0.01,
        'styrene': 1e-12,
    }},
    polymerPhase=pp,
    terminationTime=(1.0, 's'),
    sensitivity=None,
    constant_gas_volume=False,
)

model(
    toleranceMoveToCore=0.1,
    toleranceInterruptSimulation=0.1,
    filterReactions=False,
    filterThreshold=100000000.0,
    maxNumObjsPerIter=1,
    terminateAtMaxObjects=False,
)

simulator(atol=1e-16, rtol=1e-08)

options(
    name='i099',
    generateSeedEachIteration=False,
    saveSeedToDatabase=False,
    units='si',
    generateOutputHTML=False,
    generatePlots=False,
    saveSimulationProfiles=True,
    verboseComments=False,
    saveEdgeSpecies=False,
    keepIrreversible=False,
    wallTime='00:00:20:00',
)

generatedSpeciesConstraints(
    allowed=['input species', 'seed mechanisms', 'reaction libraries'],
    maximumCarbonAtoms=8,
    maximumOxygenAtoms=2,
    maximumNitrogenAtoms=0,
    maximumRadicalElectrons=2,
)
"""


def main():
    for arm, pool in (("scalar", POOL_SCALAR), ("arrhenius", POOL_ARRHENIUS)):
        for T in TEMPERATURES:
            d = os.path.join(HERE, f"{arm}_T{int(T)}")
            os.makedirs(d, exist_ok=True)
            body = (HEADER.format(arm=arm, T=T)
                    + pool.format(A_OUTLET=A_OUTLET, A_SCISSION=A_SCISSION,
                                  N_SCISSION=N_SCISSION, EA_SCISSION=EA_SCISSION)
                    + TAIL.format(T=T))
            with open(os.path.join(d, "input.py"), "w") as fh:
                fh.write(body)
            print("wrote", os.path.join(d, "input.py"))


if __name__ == "__main__":
    main()
