# 5 torr argon PlasmaReactor with the electron energy balance (I-274): Te is solved from a
# specified absorbed power. ENGINEERING INTERMEDIATE: absorbedPower is ILLUSTRATIVE, not measured.
# Needs the plasma RMG-database (PlasmaArgon, PlasmaRadiativeRecombination) named in ./rmgrc
# (see rmgrc.template). The elastic rate of Ar is the Maxwell average of the LXCat Phelps
# momentum-transfer cross section (www.lxcat.net, retrieved 2026-09-23), fitted over 0.5-3 eV.
# Generated by the I-274 runs' make_deck.py --power 0.5; test/rmgpy/rmg/inputTest.py pins its
# declarations.
# I-274 energy-balance arm: P_abs = 0.5 W (ILLUSTRATIVE, not measured), Te0 = 1.0 eV,
# radius = 5.0 cm, ion mobility x1.0, entry 91 = on, atol = 1e-16, K_el = lxcat x1.0. ENGINEERING INTERMEDIATE.
# K_el source: LXCat Phelps EFFECTIVE sigma_m, www.lxcat.net retrieved 2026-09-23, Maxwell-averaged, fit 0.5-3 eV
database(
    thermoLibraries=['primaryThermoLibrary', 'PlasmaCationThermo', 'electrocatThermo', 'PlasmaExcitedNeutralThermo'],
    reactionLibraries=['PlasmaArgon', 'PlasmaRadiativeRecombination'],
    seedMechanisms=[],
    kineticsDepositories=['training'],
    kineticsFamilies=['Plasma_Electron_Attachment'],
    kineticsEstimator='rate rules',
)

species(label='e-', reactive=True, structure=adjacencyList("1 e u1 p0 c-1"))
species(label='Ar', reactive=True, structure=adjacencyList("""
1 Ar u0 p4 c0
"""))
species(label='Arp', reactive=True, structure=adjacencyList("""
multiplicity 2
1 Ar u1 p3 c+1
"""))
species(label='Ars', reactive=True, structure=adjacencyList("""
multiplicity 3
1 Ar u2 p3 c0
"""))

plasmaReactor(
    temperature=(298.15, 'K'),
    pressure=(5, 'torr'),
    electronTemperature=(11604.51812, 'K'),
    electronDensity=(1e+16, 'm^-3'),
    initialMoleFractions={'Ar': 1.0, 'Ars': 0.0},
    chargeBalanceSpecies='Arp',
    chamberGeometry={'shape': 'cylinder', 'radius': (5.0, 'cm'), 'length': (30, 'cm')},
    ionReducedMobility=(0.0001535, 'm^2/(V*s)'),
    wallRecycling=1.0,
    wallNeutralizationProducts={'Arp': 'Ar'},
    wallNeutralDiffusion={'Ars': {'product': 'Ar', 'diffusivity': (47.0, 'cm^2*torr/s')}},
    ionisationSource=(6.6e4, 'm^-3/s'),
    electronEnergyBalance={'absorbedPower': (0.5, 'W'), 'sheath': 'floatingWall', 'elasticCollisions': {'Ar': {'A': (1.801726711209142e-14, 'm^3/s'), 'n': 1.5409569651442587, 'b': -0.019608394905836768, 'c': -0.057221062443922666}, 'Ars': {'ignore': 'metastable fraction ~5e-8 of the gas: its elastic loss is < 1e-7 of the ground state and is not modelled'}}, 'electronEnergies': {'PlasmaArgon:86': (15.75961, 'eV'), 'PlasmaArgon:87': (11.548354, 'eV'), 'PlasmaArgon:88': (4.2112560000000006, 'eV'), 'PlasmaArgon:89': (-11.548354, 'eV'), 'PlasmaArgon:90': (-7.337097999999999, 'eV'), 'PlasmaArgon:91': (0.07523800000000058, 'eV'), 'PlasmaRadiativeRecombination:1': (0.0, 'eV')}},
    terminationSteadyState=1e-6,
    terminationTime=(600.0, 's'),
)

simulator(atol=1e-16, rtol=1e-8)

model(toleranceKeepInEdge=0.0, toleranceMoveToCore=0.5, toleranceInterruptSimulation=1e8, maximumEdgeSpecies=200)

options(units='si', generateOutputHTML=False, generatePlots=False, saveEdgeSpecies=True,
        saveSimulationProfiles=True, generateRMSYAML=False, generateCanteraYAML2=True)
