"""Target-only checks. Kept outside reference: the oracle never imports met."""
import ast
from datetime import datetime
import hashlib
import importlib.util
import json
import math
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
REFERENCE = ROOT / 'reference'
TARGET = next(p/'rmgpy/kmc/met.py' for p in ROOT.parents if (p/'rmgpy/kmc/met.py').is_file())


def assert_generation_inputs_equivalent(old, current, old_source, current_source):
    """Authoring may add independent cohorts, never change their generator."""
    def physical(cfg):
        snapshot={key:value for key,value in cfg.items() if key!='allocation'}
        snapshot['cases']=[{key:value for key,value in case.items() if key!='precision_stages'}
                           for case in cfg['cases']]
        return snapshot
    if not (physical(old)==physical(current)):
        raise AssertionError('physical inputs or per-run allocation changed')
    functions={'mapped_parameters','mode_coefficients','advance_modes','projected_site',
               'minimum_image','hazard','simulate','mean_se','sampler_checks',
               'independent_bead_contact','mode_grid_contact','contact_checks',
               'ewald_constant','log_upper_difference','qualify','pooled_hazard'}
    def definitions(source):
        tree=ast.parse(source)
        result={node.name:ast.dump(node,include_attributes=False) for node in tree.body
                if isinstance(node,ast.FunctionDef) and node.name in functions}
        if not (set(result)==functions):
            raise AssertionError('incomplete generator identity check')
        return result
    if not (definitions(old_source)==definitions(current_source)):
        raise AssertionError('physical generator or numerical checks changed')


def assert_generation_history(cfg, reference, versions):
    """A03 permits only fresh cohorts generated by these exact current bytes."""
    source=(REFERENCE/'run.py').read_bytes()
    inputs=(REFERENCE/'parameters.json').read_bytes()
    sha=lambda data:hashlib.sha256(data).hexdigest()
    if not (reference['parameters_sha256']==sha(inputs)):
        raise AssertionError('reference input fingerprint differs')
    if not (reference['program_sha256']==sha(source)):
        raise AssertionError('reference program fingerprint differs')
    if not (reference['versions']==versions):
        raise AssertionError('reference software versions differ')
    current_pair=(sha(inputs),sha(source))
    count=max(case.get('precision_stages',cfg['precision_stages']) for case in cfg['cases'])
    if not (len(reference['generation_provenance'])==count):
        raise AssertionError('reference generation stage count differs')
    for stage,record in enumerate(reference['generation_provenance']):
        if not (record['precision_stage']==stage):
            raise AssertionError('reference generation stage order differs')
        eligible=[case['name'] for case in cfg['cases']
                  if stage < case.get('precision_stages',cfg['precision_stages'])]
        if not (record['cases']==eligible):
            raise AssertionError('reference generation cases differ')
        pair=(record['parameters_sha256'],record['program_sha256'])
        if not (pair==current_pair):
            raise AssertionError('reference generation fingerprints differ')
        if not (record['driver_program_sha256']==current_pair[1]):
            raise AssertionError('reference generation driver differs')


def read_policy(cfg):
    raw=(ROOT/'acceptance_policy.json').read_bytes()
    policy=json.loads(raw)
    if not (policy['numerical_uncertainty']['method']==cfg['uncertainty_method']):
        raise AssertionError('numerical uncertainty method differs from policy')
    if not (policy['numerical_uncertainty']['marginal_sigmas']==cfg['statistical_sigmas']):
        raise AssertionError('sampling allowance differs from policy')
    model=policy['model_tolerance']
    if not (model['relative_fraction']>=0):
        raise AssertionError('model tolerance must be nonnegative')
    if not (math.isclose(model['symmetric_log'],math.log1p(model['relative_fraction']),abs_tol=1e-15)):
        raise AssertionError('model log tolerance differs from its relative allowance')
    if not (math.isclose(model['factor'],math.exp(model['symmetric_log']),rel_tol=1e-15)):
        raise AssertionError('model tolerance factor differs from its log allowance')
    return policy,hashlib.sha256(raw).hexdigest()


def assert_decision_order():
    events=json.loads((ROOT/'decision_order.json').read_text())['events']
    indexed={row['event']:row for row in events}
    def instant(value):
        return datetime.fromisoformat(value.replace(' UTC','+00:00').replace(' ','T',1))
    if not ([instant(row['at_utc']) for row in events]==sorted(instant(row['at_utc']) for row in events)):
        raise AssertionError('recorded decision timestamps are out of order')
    if not (instant(indexed['declare_model_and_numerical_policy']['at_utc']) < instant(indexed['start_corrected_reference_measurement']['at_utc']) < instant(indexed['start_corrected_candidate_comparison']['at_utc'])):
        raise AssertionError('recorded policy declaration does not precede measurement and comparison')
    policy=json.loads((ROOT/'acceptance_policy.json').read_bytes())
    declaration_commit=indexed['start_corrected_reference_measurement']['policy_commit']
    original=subprocess.check_output(['git','show',declaration_commit+':test/rmgpy/kmc/fixtures/i030_kernel_reference/acceptance_policy.json'],cwd=ROOT)
    digest=hashlib.sha256(original).hexdigest()
    if policy.get('original_declaration_sha256',digest)!=digest:
        raise AssertionError('original policy declaration fingerprint differs')
    declared=json.loads(original)
    # Owner approval is later metadata; the pre-measurement numerical policy
    # and model allowance must still equal the original committed declaration.
    unchanged=dict(policy)
    unchanged.pop('original_declaration_sha256',None)
    unchanged.pop('owner_ruling',None)
    unchanged['model_tolerance']=dict(unchanged['model_tolerance'])
    unchanged['model_tolerance'].pop('owner_approved_on',None)
    unchanged['model_tolerance']['status']=declared['model_tolerance']['status']
    if unchanged!=declared:
        raise AssertionError('original numerical or model policy changed')
    if not (indexed['start_corrected_reference_measurement']['policy_sha256']==digest):
        raise AssertionError('measurement record has a different policy fingerprint')
    if not (indexed['start_corrected_candidate_comparison']['policy_sha256']==digest):
        raise AssertionError('comparison record has a different policy fingerprint')
    if not (indexed['start_corrected_reference_measurement']['reference_program_sha256']==hashlib.sha256((REFERENCE/'run.py').read_bytes()).hexdigest()):
        raise AssertionError('measurement record has a different reference program fingerprint')
    if not (indexed['start_corrected_reference_measurement']['parameters_sha256']==hashlib.sha256((REFERENCE/'parameters.json').read_bytes()).hexdigest()):
        raise AssertionError('measurement record has a different parameter fingerprint')
    if not (indexed['start_corrected_candidate_comparison']['reference_results_sha256']==hashlib.sha256((REFERENCE/'results/results.json').read_bytes()).hexdigest()):
        raise AssertionError('comparison record has a different reference result fingerprint')
    return indexed['start_corrected_reference_measurement']['policy_commit']


def load_target(transform=None):
    raw = TARGET.read_bytes()
    source = raw.decode()
    if transform:
        source = transform(source)
    spec = importlib.util.spec_from_file_location('met_reference_target', TARGET)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    exec(compile(source, str(TARGET), 'exec'), module.__dict__)
    if not (TARGET.read_bytes() == raw):
        raise AssertionError('target changed during import')
    module._source_sha256 = hashlib.sha256(raw).hexdigest()
    return module


def target_checks(module, cfg, reference):
    policy,policy_hash=read_policy(cfg)
    model_log=policy['model_tolerance']['symmetric_log']
    arm = module.TRANSPORT_ARMS[cfg['rouse_arm']]
    anchors = []
    def anchor(name, actual, expected):
        anchors.append({'name':name, 'actual':actual, 'literal':expected,
                        'pass':math.isclose(actual, expected, rel_tol=2e-12, abs_tol=0.)})
    anchor('D0', arm.d0(cfg['temperature_K']), cfg['D0_m2_s'])
    anchor('sigma0', module.SIGMA_CONTACT, cfg['sigma0_m'])
    anchor('boltzmann', module.K_B, cfg['boltzmann_J_K'])
    anchor('avogadro', module.N_A, cfg['avogadro_mol_inverse'])
    anchor('Rg_squared_per_unit', module.PS_C_R2*module.PS_M0/6, cfg['Rg_squared_per_unit_m2'])
    for label, chain in cfg['chains'].items():
        anchor('D_CM_N'+label, arm.chain_diffusivity(cfg['temperature_K'], chain['units']), chain['D_CM_m2_s'])
        anchor('kernel_Rg_N'+label, math.sqrt(module.PS_C_R2*module.PS_M0*chain['units']/6), chain['kernel_Rg_m'])
    comparison, branches, transient_diagnostics = [], [], []
    indexed = {(r['case'],r['pair_class']):r for r in reference['qualification']}
    transient={(r['case'],r['pair_class']):r for r in reference['simulation'] if r['name']=='transient'}
    for case in cfg['cases']:
        left = cfg['chains'][str(case['units_i'])]
        right = cfg['chains'][str(case['units_j'])]
        radius = max(cfg['sigma0_m'], 2*min(left['kernel_Rg_m'], right['kernel_Rg_m']))
        literal_rate = (4*math.pi*cfg['avogadro_mol_inverse']*cfg['spin_factor']
                        *(left['D_CM_m2_s']+right['D_CM_m2_s'])*radius)
        for pair in cfg['pair_classes']:
            actual = module.diffusion_rate(arm, cfg['temperature_K'], left['units'], right['units'], pair,
                                           spin_factor=cfg['spin_factor'])
            ref = indexed[(case['name'],pair)]
            ratio = actual/(ref['reference_reduced']*ref['rate_unit_m3_mol_s'])
            branches.append({'case':case['name'], 'pair_class':pair, 'actual':actual,
                             'literal_rule':literal_rate,
                             'pass':math.isclose(actual,literal_rate,rel_tol=2e-12)})
            deviation=abs(math.log(ratio))
            numerical=ref['total_log_tolerance']
            residual=max(0.,deviation-numerical)
            within = deviation <= numerical+model_log
            comparison.append({'case':case['name'], 'pair_class':pair,
                               'candidate_m3_mol_s':actual, 'candidate_over_reference':ratio,
                               'absolute_log_deviation':deviation,
                               'numerical_log_band':numerical, 'proposed_model_log_band':model_log,
                               'combined_log_band':numerical+model_log,
                               'numerical_log_consumed':min(deviation,numerical),
                               'residual_model_log_required':residual,
                               'proposed_model_log_consumed':min(residual,model_log),
                               'log_excess_beyond_both':max(0.,residual-model_log),
                               'within_numerical_only':deviation<=numerical,
                               'within_error_budget':within, 'reference_qualified':ref['qualified'],
                               'accepted':within and ref['qualified']})
            for item in transient[(case['name'],pair)]['transient']['bins']:
                k,s=item['k_reduced'],item['se_reduced']
                reduced=actual/ref['rate_unit_m3_mol_s']
                bound=cfg['transient_relative_allowance']*k+cfg['statistical_sigmas']*s
                transient_diagnostics.append({'case':case['name'],'pair_class':pair,
                    't1':item['t1'],'t2':item['t2'],'reference_reduced':k,'se_reduced':s,
                    'candidate_reduced':reduced,'candidate_over_finite_box_reference':reduced/k if k else None,
                    'diagnostic_absolute_band':bound,'diagnostic_agreement':abs(reduced-k)<=bound,
                    'policy':'report-only; no acceptance'})
    return {'met_source_sha256':module._source_sha256, 'anchors':anchors,
            'acceptance_policy_sha256':policy_hash,
            'model_tolerance_status':policy['model_tolerance']['status'],
            'literal_kernel_branches':branches, 'comparison':comparison,
            'transient_reporting_only':transient_diagnostics,
            'transport_pass':all(row['pass'] for row in anchors),
            'branch_pass':all(row['pass'] for row in branches),
            'adoption_pass':all(row['accepted'] for row in comparison)}


def assert_transport_and_branches(report):
    if not (report['transport_pass']):
        raise AssertionError('target transport or Rg differs from literal inputs')
    if not (report['branch_pass']):
        raise AssertionError('target min/floor/two-chain radius rule differs from literal contract')


def assert_scientific_acceptance(report):
    assert_transport_and_branches(report)
    if not (all(row['reference_qualified'] for row in report['comparison'])):
        raise AssertionError('Rouse oracle is not numerically qualified')
    if not (all(row['within_error_budget'] for row in report['comparison'])):
        raise AssertionError('kernel exceeds numerical plus proposed model band')


def assert_owner_approved_adoption(report,cfg):
    """Bind the approved passing rows and report the two recorded deviations."""
    assert_transport_and_branches(report)
    policy,policy_hash=read_policy(cfg)
    model=policy['model_tolerance']
    ruling=policy.get('owner_ruling',{})
    if (model.get('owner_approved_on')!='2026-10-04'
            or model['status']!='APPROVED by owner on 2026-10-04'
            or ruling.get('approved_on')!='2026-10-04'
            or model['relative_fraction']!=0 or model['symmetric_log']!=0):
        raise AssertionError('zero model tolerance requires the recorded owner approval')
    records=ruling.get('known_deviations',[])
    approved_keys={('N4_N16','end/end'),('N16_N4','end/end')}
    known={(row['case'],row['pair_class']):row for row in records}
    if len(records)!=2 or set(known)!=approved_keys:
        raise AssertionError('known-deviation list differs from the owner ruling')
    expected={(case['name'],pair) for case in cfg['cases'] for pair in cfg['pair_classes']}
    rows={(row['case'],row['pair_class']):row for row in report['comparison']}
    if len(rows)!=len(report['comparison']) or set(rows)!=expected:
        raise AssertionError('binding adoption requires complete, unique case/pair coverage')
    passing=[]
    deviations=[]
    for key,row in rows.items():
        if not row['reference_qualified']:
            raise AssertionError('Rouse oracle is not numerically qualified')
        if key not in known:
            if not row['within_error_budget'] or not row['accepted']:
                raise AssertionError('unexpected failing row: '+':'.join(key))
            passing.append(':'.join(key))
            continue
        record=known[key]
        measured=record['measured_candidate_over_reference']
        tolerance=record['record_relative_tolerance']
        if (record.get('owner_approved_on')!='2026-10-04'
                or tolerance!=2e-12 or not math.isfinite(measured) or measured<=0):
            raise AssertionError('invalid owner-approved known-deviation record')
        if not math.isclose(row['candidate_over_reference'],measured,rel_tol=tolerance,abs_tol=0.):
            raise AssertionError('known deviation moved outside its reported record: '+':'.join(key))
        if row['within_error_budget'] or row['accepted']:
            raise AssertionError('known deviation no longer matches its recorded failure: '+':'.join(key))
        deviations.append(dict(record,observed_candidate_over_reference=row['candidate_over_reference'],
                               status='reported known deviation; scientific comparison fails'))
    if len(passing)!=16 or ruling.get('passing_row_count')!=16:
        raise AssertionError('binding adoption requires all sixteen ordinary rows to pass')
    return {'owner_approved_on':'2026-10-04','policy_sha256':policy_hash,
            'model_tolerance_relative_fraction':0.,'passing_rows':passing,
            'known_deviations':deviations,'binding_adoption_pass':True}


def render_candidate(report):
    lines = ['<!-- BEGIN CANDIDATE NUMBERS -->', '',
             '| Case | Pair | Candidate (m3 mol-1 s-1) | Candidate / reference | Absolute log deviation | Numerical band | Model band (owner-approved) | Numerical consumed | Model consumed | Residual model required | Excess | Qualified | Within zero-model band |',
             '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---|']
    for row in report['comparison']:
        lines.append(f"| {row['case']} | {row['pair_class']} | {row['candidate_m3_mol_s']:.9g} | {row['candidate_over_reference']:.8g} | {row['absolute_log_deviation']:.6f} | {row['numerical_log_band']:.6f} | {row['proposed_model_log_band']:.6f} | {row['numerical_log_consumed']:.6f} | {row['proposed_model_log_consumed']:.6f} | {row['residual_model_log_required']:.6f} | {row['log_excess_beyond_both']:.6f} | {row['reference_qualified']} | {row['within_error_budget']} |")
    lines += ['', 'Consumption is bookkeeping: numerical allowance is used first, then model allowance. It does not estimate a physical model-error component.', '',
              '| Case | Pair | t1 | t2 | Candidate / finite-box reference | 20% + 4 SE diagnostic (REPORT-ONLY) |',
              '|---|---|---:|---:|---:|---|']
    for row in report['transient_reporting_only']:
        ratio=row['candidate_over_finite_box_reference']
        ratio_text=f'{ratio:.7g}' if ratio is not None else 'undefined (no events)'
        lines.append(f"| {row['case']} | {row['pair_class']} | {row['t1']:g} | {row['t2']:g} | {ratio_text} | {row['diagnostic_agreement']} (report-only) |")
    lines += ['', f"Literal transport anchors: {sum(r['pass'] for r in report['anchors'])}/{len(report['anchors'])}.",
              f"Literal min/floor/two-chain branches: {sum(r['pass'] for r in report['literal_kernel_branches'])}/{len(report['literal_kernel_branches'])}.",
              f"Strict zero-model scientific comparison passed: {report['adoption_pass']}.",
              f"Model tolerance status: {report['model_tolerance_status']}.", '', '<!-- END CANDIDATE NUMBERS -->']
    return '\n'.join(lines)+'\n'
