#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[Li] => [Lip]",
    degeneracy = 1.0,
    reversible = False,
    kinetics = VoronovEIArrhenius(A=(1.39e-07,'cm^3/(molecule*s)'), P=0, X=0.438, K=0.41, dE=(5.4, 'eV'), electrons=1, Tmin=(11604.5,'K'), Tmax=(2.3209e+08,'K'), comment="""Voronov (1997) e-impact ionization fit, Z=3, N=3 """),
    longDesc = 
"""
Originally from reaction library: PlasmaElectronImpactIonization
Voronov (1997) e-impact ionization fit, Z=3, N=3
""",
)

entry(
    index = 1,
    label = "[Lip] => [Li]",
    degeneracy = 1.0,
    reversible = False,
    kinetics = BadnellRRArrhenius(A=(8.7e-12,'cm^3/(molecule*s)'), B=0.364, T0=(147,'K'), T1=(7.153e+06,'K'), C=0.1508, T2=(715400,'K'), electrons=-1, Tmin=(10,'K'), Tmax=(1e+07,'K'), comment="""Badnell (2006) RR fit, Z=3, N=2"""),
    longDesc = 
"""
Originally from reaction library: PlasmaRadiativeRecombination
Badnell (2006) RR fit, Z=3, N=2
""",
)

