#!/usr/bin/env python
# encoding: utf-8

name = "Electron_Carrying_Recombination/groups"
shortDesc = ""
longDesc = """
A cut-down copy of the shipped Cation_R_Recombination family: a lithium cation and a radical
recombine into a neutral closed-shell molecule, and the charge is closed by an electron that never
appears among the reactants. Everything that is not needed to exercise the electron-count load
boundary -- the fitted Marcus rules, the extended group tree -- has been dropped, but the root
group, the recipe and the electron declaration are the real family's.

The chemistry has to be genuine rather than convenient. `Reaction.is_balanced` compares the net
charges, so a reaction that consumes an electron balances only if the reactant side really is one
charge unit more positive than the product side. An earlier version of this fixture declared
`electrons = -1` over charge-neutral methyl recombination, which is not a reaction that can happen;
it survived only because the charge half of `is_balanced` was dead code.
"""

template(reactants=["Root"], products=["Y_Y"], ownReverse=False)

reverse = "Cation_Bond_Dissociation"
reversible = True

autoGenerated = True
reactantNum = 2
productNum = 1

# The reactant side carries a +1 cation and the product side is neutral, so the family both needs
# charged species allowed and needs an electron on the reactant side to close the balance. One
# electron is consumed by every reaction of this family; it is a reactant particle, but it is never
# listed among the reactants -- this declaration is the only record of it.
allowChargedSpecies = True
electrons = -1

recipe(
    actions=[
        ["LOSE_CHARGE", "*1", 1],
        ["FORM_BOND", "*1", 1, "*2"],
        ["LOSE_RADICAL", "*2", 1],
    ]
)

entry(
    index=0,
    label="Root",
    group="""
1 *1 Li+ u0 p0 c+1
2 *2 R   u1
""",
    kinetics=None,
)

tree(
    """
L1: Root
"""
)
